### ISSUE TITLE
Apk update , detected by Google Play Protect 

### ISSUE THREAD

**Issue by mozzaru** [null2264/yokai#1]
### Steps to reproduce

Detected by Google Play Protect 

### Expected behavior

.

### Actual behavior

.

### Crash logs

.

### TachiyomiJ2K version

1.7.6

### Android version

Android 11

### Device

Realme 7i

### Other details

![Screenshot_2024-01-15-13-38-08-23_b5a5c5cb02ca09c784c5d88160e2ec24](https://github.com/null2264/yokai/assets/100791931/14b75eb0-4532-47a7-a273-2363bc5b9e3c)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I am reporting an issue exclusive to this fork. I have also checked that is not an issue on the [main version of Tachiyomi](https://github.com/tachiyomiorg/tachiyomi)
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.7.3](https://github.com/Jays2Kings/tachiyomiJ2K/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I have filled out all of the requested information in this form.

**Comment by mozzaru** [comment]
I want to update the apk then I want to install it then Google Play Protect appears

**Comment by null2264** [comment]
Tap "More Details" -> "Install Anyway", it's normal Google Play Protect stuff since it's a new app...

**Comment by maod65104-hash** [comment]
Likely maintainer: @null2264 (Ahmad Ansori Palembani).

**Comment by maod65104-hash** [comment]
Likely maintainer: @null2264 (null2264).
