### ISSUE TITLE
Not getting covers and descriptions (yokai-only)

### ISSUE THREAD

**Issue by lalalasupa0** [null2264/yokai#102]
### Steps to reproduce

Go to source (MangaDex in my case as a test)
Search manga (Air Gear in my case)
Open manga

### Expected behavior

Should be able to see covers and description

### Actual behavior

![Screenshot_20240616_222223_Ykai Nightly](https://github.com/null2264/yokai/assets/101371218/77b28e81-1ab0-4d9d-9c6b-0b834db46949)
![Screenshot_20240616_222231_Ykai Nightly](https://github.com/null2264/yokai/assets/101371218/5569eb7a-a92e-4c07-8bd6-2b85bb9a6f57)

### Yōkai version

App version: 1.8.4-r5296 (standard, 8d9e5813a, 138, 2024-06-17T03:15:15Z) Android version: 12 (SDK 31) Android build ID: SP1A.210812.016.G975FXXSGHWA3 Device brand: samsung Device manufacturer: samsung Device name: beyond2 Device model: SM-G975F Device product name: beyond2ltexx

### Android version

Android 12

### Device

Samsung S10+

### Other details

It started happening while migrating in the migration section in "browser" out of nowhere, I don't know if it's a problem that started with the update
It happens with Comick, MangaDex, BATO and so on

Not happening in Mihon

Not an user agent nor dns over https issue

In the web there are covers and descriptions

Only happens with brand new mangas

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, or a request for an extension, I should be contacting the extensions repository's maintainer/support for help.
- [X] I am reporting an issue exclusive to this fork. I have also checked that is not an issue on the [main version of Mihon](https://github.com/mihonapp/mihon)
- [X] I have tried the [troubleshooting guide](https://mihon.app/help/).
- [X] I have updated the app to version **[1.8.4](https://github.com/null2264/yokai/releases/latest)**.
- [X] I have updated all installed extensions.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I have filled out all of the requested information in this form.

**Comment by lalalasupa0** [comment]
@null2264 
![Screenshot_20240617_055827_Ykai Nightly](https://github.com/null2264/yokai/assets/101371218/9b330364-99cf-4050-a65e-b484c57706e6)
Not getting descriptions yet

**Comment by null2264** [comment]
Oh right, forgot about that
