### ISSUE TITLE
Local source not full loading and crashing the app

### ISSUE THREAD

**Issue by lalalasupa0** [null2264/yokai#115]
### Steps to reproduce

Open local source

### Expected behavior

Should load the stuff there

### Actual behavior

https://github.com/null2264/yokai/assets/101371218/a4998d35-4528-4c3d-87c3-4300e9ea66a0

(At the end of the vid I get a delete cache thing, and doing so doesn't help)

### Crash logs

No crash logs

### Yōkai version

App version: 1.8.4.1-r5404 (standard, 78a9e1dc0, 138, 2024-06-28T04:33:29Z) Android version: 12 (SDK 31) Android build ID: SP1A.210812.016.G975FXXSGHWA3 Device brand: samsung Device manufacturer: samsung Device name: beyond2 Device model: SM-G975F Device product name: beyond2ltexx

### Android version

Android 12

### Device

Samsung S10+

### Other details

Local source loading is always been slow, but this is the first time this has ever happened to me
It started after, maybe the last 2 nightly updates? I'm not sure but at least a week ago I was entering the local source as usual

Something I would like to mention, this doesn't happen in my secure folder (samsung's), this is just outside it
My local source is located in my sdcard, I hope that has nothing to do with it... The local source was working just fine before, and I haven't done anything to my storage in any way

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, or a request for an extension, I should be contacting the extensions repository's maintainer/support for help.
- [X] I am reporting an issue exclusive to this fork. I have also checked that is not an issue on the [main version of Mihon](https://github.com/mihonapp/mihon)
- [X] I have tried the [troubleshooting guide](https://mihon.app/help/).
- [X] I have updated the app to version **[1.8.4.1](https://github.com/null2264/yokai/releases/latest)**.
- [X] I have updated all installed extensions.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I have filled out all of the requested information in this form.

**Comment by null2264** [comment]
Huh, I thought I fixed this crash already, did you perhaps use EPUB? I honestly forget to check EPUB

**Comment by lalalasupa0** [comment]
> Huh, I thought I fixed this crash already, did you perhaps use EPUB? I honestly forget to check EPUB

I do have epubs in my local source, but that has never cause anything to me so idk, and before this I hadn't added any new epub that could be the cause either
