### ISSUE TITLE
Local source not loading the cover for some mangas

### ISSUE THREAD

**Issue by lalalasupa0** [null2264/yokai#116]
### Steps to reproduce

Check manga in local sorce
The manga has cover.*** image file: yes
Open local source
Go to the manga you just checked

### Expected behavior

Should show the cover like usual

### Actual behavior

![Screenshot_20240629_232030_Ykai Nightly](https://github.com/null2264/yokai/assets/101371218/6fc4eeed-7d23-4bc4-9b1d-82a53333efb4)
![Screenshot_20240629_232056_Ykai Nightly](https://github.com/null2264/yokai/assets/101371218/82103521-1054-47aa-a4e0-a1d4ca7b248a)

### Yōkai version

App version: 1.8.4.1-r5407 (standard, 3b60b0069, 138, 2024-06-30T03:10:34Z) Android version: 12 (SDK 31) Android build ID: SP1A.210812.016.G975FXXSGHWA3 Device brand: samsung Device manufacturer: samsung Device name: beyond2 Device model: SM-G975F Device product name: beyond2ltexx

### Android version

Android

### Device

Samsung s10+

### Other details

My local source is on my memory card

.nomedia file is in all my folders (mangas)

Using Y Nightly

This happens in like 2 or 1 or 0 mangas in every arrow, not in all of them

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, or a request for an extension, I should be contacting the extensions repository's maintainer/support for help.
- [X] I am reporting an issue exclusive to this fork. I have also checked that is not an issue on the [main version of Mihon](https://github.com/mihonapp/mihon)
- [X] I have tried the [troubleshooting guide](https://mihon.app/help/).
- [X] I have updated the app to version **[1.8.4.1](https://github.com/null2264/yokai/releases/latest)**.
- [X] I have updated all installed extensions.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I have filled out all of the requested information in this form.

**Comment by lalalasupa0** [comment]
I hope this gets fixed soon, it's very important imo... :(

**Comment by null2264** [comment]
I added  "Invalidate cover" button, you can try using it to see if it fixed it (since it could be Smasnug's custom rom messing with it when the manga being added to the app): Go to local source manga with invalid cover -> Tap on triple dots -> Edit -> Invalidate cover -> Save.

**Comment by lalalasupa0** [comment]
> I added "Invalidate cover" button, you can try using it to see if it fixed it (since it could be Smasnug's custom rom messing with it when the manga being added to the app): Go to local source manga with invalid cover -> Tap on triple dots -> Edit -> Invalidate cover -> Save.

That worked !!
The only downside is that the manga _has_ to be added to the library to be able to open the edit menu, but I guess that isn't that big of a problem
Ig this should be closed

**Comment by null2264** [comment]
> the manga has to be added to the library

Oh right, I'll just make it so that the cover is invalidated when your refresh it then.

**Comment by lalalasupa0** [comment]
@null2264 
Also, wouldn't it be nice if there was something like this for manga in general and not just local source? So as not to have to delete all the saved covers to change the cover of one? For example, the option to use the first cover of mangadex, it doesn't take effect doing something as easy as just refreshin a manga
