### ISSUE TITLE
Ikigai Mangas NSFW?!

### ISSUE THREAD

**Issue by Unknoweird** [null2264/yokai#121]
### Describe your suggested feature

Ikigai Mangas has some mangas inaccessible if you don't choose the option 'NSFW' on the top right of the page. Those include action Manga and manhwas for some reason. It is possible to add an option in the app to access that mode? (I'm sorry if my English is kinda trash)

### Other details

![Screenshot_20240710-111534_Samsung Internet](https://github.com/null2264/yokai/assets/101126322/0908b121-24ea-490a-9a4e-09ef06de6366)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an request for a feature in the original Tachiyomi, I am opening because multiple versions of Yōkai have been released without this feature.
- [X] If this is an issue with an extension, or a request for an extension, I should be contacting the extensions repository's maintainer/support for help.
- [X] I have updated the app to version **[1.8.4.3](https://github.com/null2264/yokai/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [X] I will fill out all of the requested information in this form.

**Comment by null2264** [comment]
Extension issue (not even an issue tbh), next time please check extension settings first before asking for help (Browse > Extensions > Find Ikigai Mangas > NSFW, toggle that on) and this is definitely not the right place to ask about extension, if issue persists, please contact extension maintainer instead.

**Comment by Unknoweird** [comment]
I had no idea, I'm so sorry for the inconvenience
