### ISSUE TITLE
[bug] Koharu from Keiyoushi not using default reading mode

### ISSUE THREAD

**Issue by mangkoran** [null2264/yokai#125]
### Steps to reproduce

1. Set "Settings -> Reader -> Default reading mode" to "Right to left"
2. Install Koharu extension from Keiyoushi
3. Open any manga from it

### Expected behavior

Any manga opened should use Yokai's default reading mode.

### Actual behavior

Any manga opened will use "Left to right" and ignore Yokai's default reading mode.

![image](https://github.com/user-attachments/assets/72445002-64a3-4c76-aba5-292ce749b342)

### Crash logs

-

### Yōkai version

1.8.4.3

### Android version

14

### Device

Redmi Turbo 3

### Other details

I'm not sure whether this is Yokai's bug or extension's bug, but I found no reference to reading in the extension repo. However, this only happens with Koharu. Other sources are using the default just fine. I also have checked using Mihon and it's **not an issue in Mihon**.

Please let me know if you need more details regarding this issue.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, or a request for an extension, I should be contacting the extensions repository's maintainer/support for help.
- [X] I am reporting an issue exclusive to this fork. I have also checked that is not an issue on the [main version of Mihon](https://github.com/mihonapp/mihon)
- [X] I have tried the [troubleshooting guide](https://mihon.app/help/).
- [X] I have updated the app to version **[1.8.4.3](https://github.com/null2264/yokai/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have filled out all of the requested information in this form.

**Comment by null2264** [comment]
It's a J2K behaviour where it overwrite the Reading mode from default to Long Strip if it's a manhwa or LTR if it's a manhua/comic. No way to disable it at the moment (not sure why it wasn't an option tbh).

**Comment by mangkoran** [comment]
@null2264 well yes I could click "Use Default" but well this is still a bug :)

In the meanwhile, we can leave this issue open to track this.

Anyway, thank you for your work with this fork!

**Comment by null2264** [comment]
> well yes I could click "Use Default" but well this is still a bug

Not exactly a bug, Koharu probably use Manhua or Comic tag for all their entries. The only workaround I could think of is to give an option to disable the "smart reading mode" feature entirely.

**Comment by mangkoran** [comment]
Oh wait then this could be considered as extension bug? If so I will open an issue in Keiyoushi

**Comment by null2264** [comment]
Nah, it's probably Koharu behaviour... sources can be weird sometimes

**Comment by mangkoran** [comment]
I mean, if it can be overridden extension side, it could be a workaround. Most Koharu content is manga anyways.

**Comment by null2264** [comment]
Yep, it detects the tag "english" so it automatically use LTR

**Comment by mangkoran** [comment]
Just quick scanning through the repo. I suppose these are the tags used to detect comic type?

https://github.com/null2264/yokai/blob/91656140e5f5ceefdf1424d08663e2a893d2e524/app/src/main/java/eu/kanade/tachiyomi/data/database/models/Manga.kt#L249-L251

**Comment by null2264** [comment]
Yes, also here

https://github.com/null2264/yokai/blob/91656140e5f5ceefdf1424d08663e2a893d2e524/app/src/main/java/eu/kanade/tachiyomi/data/database/models/Manga.kt#L209-L217

**Comment by mangkoran** [comment]
The manga above is indeed have tag "english" on it. How if we remove `tag.startsWith("english")` in above lines? I'm not sure if this is a good condition/filter for comic type (the filter was last updated 3 years ago btw). We do have more manga content than comic anyway.

![image](https://github.com/user-attachments/assets/225510ff-de80-488c-9949-9968b8833f99)

**Comment by null2264** [comment]
I don't mind personally, feel free to open a PR.

**Comment by sandesh-404** [comment]
The same is true for me with manganato extension.

**Comment by null2264** [comment]
Not really a bug, but I guess might as well remove LTR auto detection since it seems to cause too many confusion...
