### ISSUE TITLE
Crash when manually updating the sources' repo while downloading an extension update

### ISSUE THREAD

**Issue by MrDfour** [null2264/yokai#130]
### Steps to reproduce

I was downloading an update for a given extension, since it was taking some time I went to the screen to add repo url and did a manual update. Went out, tried to search for some other extension, went to the languages filter and then it crashed
![Screenshot_2024-07-27-01-09-17-427_eu kanade tachiyomi yokai](https://github.com/user-attachments/assets/12f9e4bf-282b-454d-8e2b-83e8ab086f9e)

### Expected behavior

Should crash

### Actual behavior

Crashes

### Crash logs

Sorry I lost the crash dump due dumb miui

### Yōkai version

1.8.4.3

### Android version

Android 14

### Device

Poco x6 Pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, or a request for an extension, I should be contacting the extensions repository's maintainer/support for help.
- [X] I am reporting an issue exclusive to this fork. I have also checked that is not an issue on the [main version of Mihon](https://github.com/mihonapp/mihon)
- [X] I have tried the [troubleshooting guide](https://mihon.app/help/).
- [X] I have updated the app to version **[1.8.4.3](https://github.com/null2264/yokai/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have filled out all of the requested information in this form.

**Comment by null2264** [comment]
It caused by connection issue, should be harmless, you can try using different connection or using VPN to fix it. I'll fix it so that it wouldn't crash if it's a connection issue later.
