### ISSUE TITLE
AniList sync not working?

### ISSUE THREAD

**Issue by lalalasupa0** [null2264/yokai#133]
### Steps to reproduce

I got error 403
I try to log out and log in again
Click anilist in sync settings
It takes me to the website, where I already have Yōkai accepted as an app and it simply redirects me to the app again

### Expected behavior

Should log me in to AniList on Yokai

### Actual behavior

Nothing happens, I just doesn't log me in

### Yōkai version

App version: 1.8.4.3-r5452 (standard, 114776bc5, 139, 2024-07-30T00:18:37Z) Android version: 12 (SDK 31) Android build ID: SP1A.210812.016.G975FXXSGHWA3 Device brand: samsung Device manufacturer: samsung Device name: beyond2 Device model: SM-G975F Device product name: beyond2ltexx

### Android version

Android 12

### Device

Samsung s10+

### Other details

I tried to revoke the app in anilist and go through the authorization process again but that didn't work either 

As I said, I was getting a 403 error before all this

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, or a request for an extension, I should be contacting the extensions repository's maintainer/support for help.
- [X] I am reporting an issue exclusive to this fork. I have also checked that is not an issue on the [main version of Mihon](https://github.com/mihonapp/mihon)
- [X] I have tried the [troubleshooting guide](https://mihon.app/help/).
- [X] I have updated the app to version **[1.8.4.3](https://github.com/null2264/yokai/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have filled out all of the requested information in this form.

**Comment by null2264** [comment]
It's AniList issue, has been happening for awhile now. It's been giving me error 500 for the last 2 days...

**Comment by lalalasupa0** [comment]
> It's AniList issue, has been happening for awhile now. It's been giving me error 500 for the last 2 days...

The not being able to log in too though? That's something that has happened to me in others like Kuukiyomi with simkl, but they fixed it on aniyomi later on so...

You think it will fix itself with time? I track everything with AniList... 😞
I also tried using Chrome to log in but didn't work too

**Comment by null2264** [comment]
> The not being able to log in too though

Unfortunately, yes.

> You think it will fix itself with time?

It should be, if they didn't introduce breaking changes (which they shouldn't, but who knows, AniList has been acting weird last few years).

**Comment by lalalasupa0** [comment]
> > The not being able to log in too though
> 
> Unfortunately, yes.
> 
> > You think it will fix itself with time?
> 
> It should be, if they didn't introduce breaking changes (which they shouldn't, but who knows, AniList has been acting weird last few years).

I updated and tried again and it worked :)))
Great
