### ISSUE TITLE
Not sorting by date fetched on beta and nightly

### ISSUE THREAD

**Issue by fedex-bermu** [null2264/yokai#134]
### Steps to reproduce

1. Update your library
2. Get new chapters for your series

### Expected behavior

Series with new chapters should be put at the top positions 

### Actual behavior

It doesn't change the sorting of the different series

### Yōkai version

App version: 1.8.5-b03

### Android version

Android version: 14 (SDK 34)

### Device

Samsung SM-S918B (dm3q)

### Other details

It wasn't happening on the stable branch. It happens also on the nightly App version: 1.8.5-r5476 (standard, 563a3a028, 140, 2024-07-31T06:16:18Z)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, or a request for an extension, I should be contacting the extensions repository's maintainer/support for help.
- [X] I am reporting an issue exclusive to this fork. I have also checked that is not an issue on the [main version of Mihon](https://github.com/mihonapp/mihon)
- [X] I have tried the [troubleshooting guide](https://mihon.app/help/).
- [X] I have updated the app to version **[1.8.4.3](https://github.com/null2264/yokai/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have filled out all of the requested information in this form.

**Comment by null2264** [comment]
Fixed on latest nightly (3fa755117fe125d034b2bcf8b50438bc62bdc0d8).
