### ISSUE TITLE
manga image does not appear

### ISSUE THREAD

**Issue by Tazjpg** [null2264/yokai#137]
### Potential workaround
- Download the chapter (also with "split tall images" option enabled just to be sure)

---

### Steps to reproduce

1. I enter the manga I want to see
2. I select the chapter
3. I swipe to read
4. The next image of the manga does not appear or is glitched

### Expected behavior

I wait a few minutes and hope that maybe the image loads but nothing happens, I reload the chapter and it doesn't work, I was hoping that maybe this way the chapter would appear 

### Actual behavior

The image of the manga disappeared or while I read there are parts of the chapter where there is empty space, which is where the image does not appear 

### Yōkai version

App version: 1.8.4.4 (standard, 8dc093858, 139, 2024-08-05T14:45:59Z)

### Android version

Android 10

### Device

Motorola e7 plus 

### Other details

https://github.com/user-attachments/assets/e9c5e59a-4fc5-4f73-80f8-fa8437528575

Video with details of the problem 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, or a request for an extension, I should be contacting the extensions repository's maintainer/support for help.
- [X] I am reporting an issue exclusive to this fork. I have also checked that is not an issue on the [main version of Mihon](https://github.com/mihonapp/mihon)
- [X] I have tried the [troubleshooting guide](https://mihon.app/help/).
- [X] I have updated the app to version **[1.8.4.4](https://github.com/null2264/yokai/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have filled out all of the requested information in this form.

**Comment by ChriszZ8** [comment]
I found the same problem as you, but when I used J2K which still had the 32 bit color off feature, the problem as you explained didn't occur, so the conclusion was "there are some devices that may not be compatible with the new 32 Bit color permanent feature" I hope Yokai returns quickly this feature.

* if you can use the 32 bit color on/off button, why make it permanent?

**Comment by null2264** [comment]
I doubt it's that, they reported that the page load properly on Mihon (I assume 0.16.5), which also have 32-bit perma enabled.

The option to disable it completely removed from upstream's API so it can't be easily done.

**Comment by Raven-621** [comment]
I also got this bug, but it looks like
<details>
  <summary>If it's too sensitive, feel free to delete this comment</summary>
It might be sources-specific problem (As in only mangas from this source that it'll have this issue on mihon and it's forks, not the source itself is the problem). 
From my list, only one source got this bug. The same manga, but from different source loads image no problem. I also tried to load a manga from that problematic source on browser. It loads just fine.
</details>

**Comment by null2264** [comment]
Might be fixed in 03043ef01bc16545ac3f79841a2fcc0d856fa90c and 153268052aa4bd460e3843f00790b2eda91fe25a

**Comment by null2264** [comment]
Partial revert: a12e1c7822381121f997e072f97ee321eeac4bef

I'll port https://github.com/mihonapp/mihon/commit/dcddac5daaff3ec89c8507c35dc13d345ffdb6d7 later

**Comment by null2264** [comment]
Probably safe to say this issue is fixed now (https://github.com/null2264/yokai/commit/01fcd7d12244156ab64bd2b5122384ac303fc314, https://github.com/null2264/yokai/commit/fd73958923bda0b6a0a522cb9ebf14f235eeca93, https://github.com/null2264/yokai/commit/c66bf9b2800aa61334a754680d0145677e968129)
