### ISSUE TITLE
"Trust all" option for extensions

### ISSUE THREAD

**Issue by kyoyacchi** [null2264/yokai#14]
### Describe your suggested feature

Can we have an trust all option for all extensions? Its struggling to enable them one by one.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an request for a feature in the original Tachiyomi, I am opening because multiple versions of Yōkai have been released without this feature.
- [X] If this is an issue with an extension, or a request for an extension, I should be contacting the extensions repository's maintainer/support for help.
- [X] I have updated the app to version **[1.7.12](https://github.com/null2264/yokai/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by null2264** [comment]
I'm waiting for the implementation of extension repo to be fully completed before I can decide if it's worth adding trust all, since I saw a rumour that Mihon is reverting back to old trust behaviour (or at least similar to it according to their `repo.json` format).

**Comment by kana-shii** [comment]
> I'm waiting for the implementation of extension repo to be fully completed before I can decide if it's worth adding trust all, since I saw a rumour that Mihon is reverting back to old trust behaviour (or at least similar to it according to their `repo.json` format).

@null2264 Recently Mihon added a trust by repo https://github.com/mihonapp/mihon/pull/570
Will you implement this?

**Comment by null2264** [comment]
Yes, a bit busy with irl, but I'll work on implementing it whenever I can.

**Comment by null2264** [comment]
> > I'm waiting for the implementation of extension repo to be fully completed before I can decide if it's worth adding trust all, since I saw a rumour that Mihon is reverting back to old trust behaviour (or at least similar to it according to their `repo.json` format).
> 
> null2264 Recently Mihon added a trust by repo [mihonapp/mihon#570](https://github.com/mihonapp/mihon/pull/570) Will you implement this?

Has been implemented on https://github.com/null2264/yokai/commit/11e66667ff29034ab2f4f6bf16bc31dbe1640617
