### ISSUE TITLE
Categorize from the manga chapter screen

### ISSUE THREAD

**Issue by akir45** [null2264/yokai#145]
### Describe your suggested feature

Allow categorization from the manga chapter screen, similar to Mihon.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an request for a feature in the original Tachiyomi, I am opening because multiple versions of Yōkai have been released without this feature.
- [X] If this is an issue with an extension, or a request for an extension, I should be contacting the extensions repository's maintainer/support for help.
- [X] I have updated the app to version **[1.8.4.5](https://github.com/null2264/yokai/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [X] I will fill out all of the requested information in this form.

**Comment by null2264** [comment]
Already in the app since J2K, you should be able to access it when you tap "In Library" button, it'll show 2 options "Remove from library" and "Edit categories" (probably won't show up if you don't have any categories). Unless you meant something else?

**Comment by akir45** [comment]
![Screenshot_2024-08-09-20-59-51-821_app mihon debug](https://github.com/user-attachments/assets/fd6a3d22-57ed-4353-b8da-ed6f252a1b0d)
I would like you to add Edit categories to the drop-down menu as shown in the image.

**Comment by null2264** [comment]
No, sorry. Adding something that already exists just to match upstream behaviour for no reason doesn't sounds right to me... Just think of it as one of J2K "unique" flow.
