### ISSUE TITLE
Yokai takes a bit longer time to open and show library specifically

### ISSUE THREAD

**Issue by Asuka-pr8** [null2264/yokai#147]
### Steps to reproduce

Open the app and show the splash screen

### Expected behavior

Takes a couple of seconds in splash screen about (2-5 sec) and shows library

### Actual behavior

Yokai takes 7-9 seconds then shows it

### Yōkai version

1.8.4.6

### Android version

13

### Device

Poco x5 pro

### Other details

Ever since I started using this fork, I've noticed it takes longer to load on the splash screen.

I didn't think much of it at first, but after trying a couple of other forks recently, I noticed that none of them took as long to load. So, I made a new backup, uninstalled Yokai, and reinstalled it, but nothing changed. Then, I tried the same backup with latest offical Mihon version, and it didn't even take 5 seconds to load on the splash screen.

It's also good to note that if yokai starting screen was recents or browse this doesn't happen and it takes 2-4 seconds to load
Samething with opening a title through a shortcut it takes 2-4 seconds

I know it's kind of silly and not a big deal, but I just wanted to point it out

App version: 1.8.4.6 (standard, ec4afe874, 139, 2024-08-10T04:35:48Z)
Android version: 13 (SDK 33)
Android build ID: TKQ1.221114.001 test-keys
Device brand: POCO
Device manufacturer: Xiaomi
Device name: redwood
Device model: 22101320G
Device product name: redwood_eea

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, or a request for an extension, I should be contacting the extensions repository's maintainer/support for help.
- [X] I am reporting an issue exclusive to this fork. I have also checked that is not an issue on the [main version of Mihon](https://github.com/mihonapp/mihon)
- [X] I have tried the [troubleshooting guide](https://mihon.app/help/).
- [X] I have updated the app to version **[1.8.4.6](https://github.com/null2264/yokai/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have filled out all of the requested information in this form.

**Comment by null2264** [comment]
Can you try the backup on [r5547](https://github.com/null2264/yokai-nightly/releases/tag/r5547)?

**Comment by Asuka-pr8** [comment]
> Can you try the backup on [r5547](https://github.com/null2264/yokai-nightly/releases/tag/r5547)?
I tested it, and indeed the issue is resolved.
I appreciate your help! And I guess I will be waiting for a new stable version then.
