### ISSUE TITLE
Kitsu tracker new domain name

### ISSUE THREAD

**Issue by C0untD0wn777** [null2264/yokai#151]
### Steps to reproduce

Kitsu just announced that they changed their domain name from kitsu.io to kitsu.app. this is due to the kitsu.io domain name expiring. I also added the official announcement from their discord.

When I try to sign in to kitsu on Yokai, it gives an unknown token error. Is it possible to change the domain on yokai to make this easier. 
![Screenshot_20240812_050642_Ykai](https://github.com/user-attachments/assets/b841e1ed-7dfe-4070-b9c9-35b21098e49e)
![Screenshot_20240812_050908_Discord](https://github.com/user-attachments/assets/c2af0b4d-73dc-4664-9900-9b033ac37f69)

### Expected behavior

When fixed, the user should be able to track what they are reading with Kitsu.

### Actual behavior

When signing in, I get the unknown token error.
![Screenshot_20240812_050642_Ykai](https://github.com/user-attachments/assets/36ecb755-6211-4a43-b378-830047c5d805)

### Yōkai version

1.8.4.6

### Android version

Android 13

### Device

Samsung Galaxy S22+

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, or a request for an extension, I should be contacting the extensions repository's maintainer/support for help.
- [X] I am reporting an issue exclusive to this fork. I have also checked that is not an issue on the [main version of Mihon](https://github.com/mihonapp/mihon)
- [X] I have tried the [troubleshooting guide](https://mihon.app/help/).
- [X] I have updated the app to version **[1.8.4.6](https://github.com/null2264/yokai/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have filled out all of the requested information in this form.

**Comment by null2264** [comment]
Already been fixed on next version (1.8.5), it'll be released later this week.

**Comment by C0untD0wn777** [comment]
Thank you
