### ISSUE TITLE
Getting duplicated chapters sometimes

### ISSUE THREAD

**Issue by lalalasupa0** [null2264/yokai#152]
### Steps to reproduce

Open manga

### Expected behavior

Chapters should be the same as those on the web.

### Actual behavior

Chapters appear duplicated, and the reader cannot advance to the next one exactly because it is a duplicate and gets stuck within the final page

![Screenshot_20240812_142228_Ykai Nightly](https://github.com/user-attachments/assets/e199275d-1579-4459-8620-1e6f7a23f40a)

### Yōkai version

App version: 1.8.5-r5551 (standard, 6c8bd82d4, 140, 2024-08-12T11:10:37Z) Android version: 12 (SDK 31) Android build ID: SP1A.210812.016.G975FXXSGHWA3 Device brand: samsung Device manufacturer: samsung Device name: beyond2 Device model: SM-G975F Device product name: beyond2ltexx

### Android version

12

### Device

s10+

### Other details

It happened to me in the Kemono extension 1.4.12 within the artist `sage・ジョー@初単行本発売中`

This doesn't happen in Mihon preview, so I don't think is a problem with the source

I got this bug before with the manga Clevatess in MangaDex's source

I don't know if the error can be reproduced for everyone, at least I hope that it can be repeated this time in the Kemono extension

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, or a request for an extension, I should be contacting the extensions repository's maintainer/support for help.
- [X] I am reporting an issue exclusive to this fork. I have also checked that is not an issue on the [main version of Mihon](https://github.com/mihonapp/mihon)
- [X] I have tried the [troubleshooting guide](https://mihon.app/help/).
- [X] I have updated the app to version **[1.8.4.6](https://github.com/null2264/yokai/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have filled out all of the requested information in this form.

**Comment by Recri97** [comment]
Tried with 1 extension(comick) enabled on [r6005](https://github.com/null2264/yokai-nightly/releases/tag/r6005) somehow it's fixed and when I enable all extension it bugged again(comick)

**Comment by Psych0naut24** [comment]
I got the same bug with a webtoon in bato extension

**Comment by null2264** [comment]
I found a way to replicate it, it only happened for me 100% of the time if the extension has ALL and EN (or other lang) variant, load the entry on ALL variant, the load the same entry on EN variant.

**Comment by null2264** [comment]
On latest nightly versions, you should now be able to workaround this by refreshing the entry when you see duplicate chapters.

**Comment by null2264** [comment]
I rework how chapters initially fetched in https://github.com/null2264/yokai/commit/2dfc1e3451804636a8e15c96eee0481c113d4fee, hopefully that fixes the issue...

**Comment by lalalasupa0** [comment]
> On latest nightly versions, you should now be able to workaround this by refreshing the entry when you see duplicate chapters.

Checked with `App version: 1.9.5-r6036 (standard, 2dfc1e3451, 154, 2024-12-17T01:49:31Z)
Android version: 11 (SDK 30)
Android build ID: RPNS31.Q1-51-40-16-12
Device brand: motorola
Device manufacturer: motorola
Device name: nairo
Device model: motorola one 5G
Device product name: nairo_a`

It works ✅
