### ISSUE TITLE
Doesn't split tall pges

### ISSUE THREAD

**Issue by Sohey44** [null2264/yokai#153]
### Steps to reproduce

All the chapters i download doesn't get split

### Expected behavior

It should split tall pages when downloaded

### Actual behavior

It just downloads them as is

### Yōkai version

1.8.4.6

### Android version

Android 6

### Device

Condor p6 plus

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, or a request for an extension, I should be contacting the extensions repository's maintainer/support for help.
- [X] I am reporting an issue exclusive to this fork. I have also checked that is not an issue on the [main version of Mihon](https://github.com/mihonapp/mihon)
- [X] I have tried the [troubleshooting guide](https://mihon.app/help/).
- [X] I have updated the app to version **[1.8.4.6](https://github.com/null2264/yokai/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have filled out all of the requested information in this form.

**Comment by null2264** [comment]
Already been fixed on 1.8.5 (https://github.com/null2264/yokai/commit/d19aca3e0b2c3c4c4d8b312731b937da7c3a1301). Will release soon
