### ISSUE TITLE
Library keep flashing or flickering

### ISSUE THREAD

**Issue by aminiqmal39** [null2264/yokai#160]
### Steps to reproduce

1. Open Yokai app.
2. Open library.
3. Scroll down at normal speed, which is slow to read title.
4. Screen keep flickering or flashing.
5. Selecting a title for moving is interrupt by flashing, making it unselect. 

### Expected behavior

The screen. When scroll down or up, perfectly without flickering or flashing.

### Actual behavior

The screen. When scroll down or up, flickering or flashing and even unselect a selecting title.

### Crash logs

No crash so far, just screen bug.

### Yōkai version

1.8.5.2

### Android version

Android 14

### Device

Xiaomi 12 Pro

### Other details

On TachiyomiJ2K v1.7.4, the screen is not flickering or flashing but selecting a title will become unselect randomly. Most often.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, or a request for an extension, I should be contacting the extensions repository's maintainer/support for help.
- [X] I am reporting an issue exclusive to this fork. I have also checked that is not an issue on the [main version of Mihon](https://github.com/mihonapp/mihon)
- [X] I have tried the [troubleshooting guide](https://mihon.app/help/).
- [X] I have updated the app to version **[1.8.5.2](https://github.com/null2264/yokai/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have filled out all of the requested information in this form.

**Comment by null2264** [comment]
Removed the video due to NSFW. But it is a known issue, haven't found the reason why the image keep being unloaded.

**Comment by aminiqmal39** [comment]
Setting phone display to refresh rate 60hz seem to reduce the flickering. I was using Auto before, my phone support up to 120hz.

**Comment by null2264** [comment]
You can ignore this reply, I'm just taking notes

---

The reason why it flickers is because the image is loaded from disk instead of memory. Not sure what caused it to not load from memory since the image load from memory just fine when switching between categories (in show only one category configuration).
