### ISSUE TITLE
Adding midou221 Repo Not Working

### ISSUE THREAD

**Issue by 8L4CK-8L4Z3** [null2264/yokai#173]
### Steps to reproduce

Tried to add the following repo after adding keiyouchi's repo: 
https://raw.githubusercontent.com/midou221/mangareader_extension/main/index.min.json

### Expected behavior

It should be added normally

### Actual behavior

I does not 

### Yōkai version

1.8.5.6

### Android version

Android 13

### Device

Honor x7

### Other details

The same repos is working in tachij2k

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, or a request for an extension, I should be contacting the extensions repository's maintainer/support for help.
- [X] I am reporting an issue exclusive to this fork. I have also checked that is not an issue on the [main version of Mihon](https://github.com/mihonapp/mihon)
- [X] I have tried the [troubleshooting guide](https://mihon.app/help/).
- [X] I have updated the app to version **[1.8.5.6](https://github.com/null2264/yokai/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have filled out all of the requested information in this form.

**Comment by null2264** [comment]
Not a Tachiyomi compatible repo.

**Comment by 8L4CK-8L4Z3** [comment]
It's working for tachiyomi j2k

**Comment by null2264** [comment]
Repo now requires `repo.json` to be seen as compatible.
