### ISSUE TITLE
Add manual migration 

### ISSUE THREAD

**Issue by WGmg23** [null2264/yokai#174]
### Describe your suggested feature

Add an option to just use normal migration like in mihon, since it's very difficult to use it to migrate since it only shows one manga

### Other details

Please 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an request for a feature in the original Tachiyomi, I am opening because multiple versions of Yōkai have been released without this feature.
- [X] If this is an issue with an extension, or a request for an extension, I should be contacting the extensions repository's maintainer/support for help.
- [X] I have updated the app to version **[1.8.5.6](https://github.com/null2264/yokai/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [X] I will fill out all of the requested information in this form.

**Comment by null2264** [comment]
Wdym? It's already there even before I forked J2K. Browse -> Migration -> Select the source (Not the all button, the source name/icon). Alternatively you can just go to the individual entry's page, tap the triple dots -> Migrate Manga/Manhwa/Manhua.
