### ISSUE TITLE
ADD THE RECENT SECTION IN THE EXTENSIONS

### ISSUE THREAD

**Issue by JipsonA** [null2264/yokai#179]
### Describe your suggested feature

I would like you to add the recent section in the different extensions like the one in the mihon application

![Imagen de WhatsApp 2024-08-31 a las 11 50 30_b4a9049d](https://github.com/user-attachments/assets/711cd2a2-29bf-4e72-8a53-d1d34e967e88)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an request for a feature in the original Tachiyomi, I am opening because multiple versions of Yōkai have been released without this feature.
- [X] If this is an issue with an extension, or a request for an extension, I should be contacting the extensions repository's maintainer/support for help.
- [X] I have updated the app to version **[1.8.5.6](https://github.com/null2264/yokai/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [X] I will fill out all of the requested information in this form.

**Comment by null2264** [comment]
Already exists

![Screenshot_2024_0901_030519.png](https://github.com/user-attachments/assets/e3c01779-da1d-478a-a6d5-24127165bdec)

**Comment by JipsonA** [comment]
oh thanks i didn't realize
