### ISSUE TITLE
Request add hidden Category

### ISSUE THREAD

**Issue by ChriszZ8** [null2264/yokai#189]
### Describe your suggested feature

![IMG_20240914_113706](https://github.com/user-attachments/assets/ba8bc997-db7b-459d-9db0-04ca03f34bc7)

### Other details

https://github.com/komikku-app/komikku/commit/6c9dfb82f4627236403d8e59171edaf183c9a2d3

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an request for a feature in the original Tachiyomi, I am opening because multiple versions of Yōkai have been released without this feature.
- [X] If this is an issue with an extension, or a request for an extension, I should be contacting the extensions repository's maintainer/support for help.
- [X] I have updated the app to version **[1.8.5.7](https://github.com/null2264/yokai/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [X] I will fill out all of the requested information in this form.

**Comment by null2264** [comment]
I personally don't see the point of this feature tbh... If it's to hide NSFW, there's a filter for it, use that instead. Already tried the feature on Aniyomi, I still don't get it...
