### ISSUE TITLE
Reacomicsonline

### ISSUE THREAD

**Issue by Unknoweird** [null2264/yokai#192]
### Steps to reproduce

1. Enter the extension 
2. Choose a comic
3. Choose a chapter 
4. Image couldn't load

### Expected behavior

Read normally 

### Actual behavior

![Screenshot_20240909-125005_Ykai](https://github.com/user-attachments/assets/70379e5d-59c8-4f84-958d-12814dae3e39)
![Screenshot_20240909-125021_Ykai](https://github.com/user-attachments/assets/7c3ec4bb-d2fe-49c5-9cf6-c3e6674b4139)

### Yōkai version

TachiJ2K 1.8.5.7

### Android version

Android 12

### Device

Galaxy A10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, or a request for an extension, I should be contacting the extensions repository's maintainer/support for help.
- [X] I am reporting an issue exclusive to this fork. I have also checked that is not an issue on the [main version of Mihon](https://github.com/mihonapp/mihon)
- [X] I have tried the [troubleshooting guide](https://mihon.app/help/).
- [X] I have updated the app to version **[1.8.5.7](https://github.com/null2264/yokai/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have filled out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
That's an extension-related issue, go check with whoever/wherever you get your extensions from. Yokai doesn't have, associate, or provide any extensions.

**Comment by Unknoweird** [comment]
How can I contact them?

**Comment by Smol-Ame** [comment]
* If you are using old Tachi extensions, those don't have support from anyone, and you will need to either search online for new extensions or search for a guide on getting extensions.
* If you can find & receive updates for your extensions, check with whoever/wherever you get said extensions from.

**Comment by Unknoweird** [comment]
Is the second one. How can I contact them?

**Comment by Smol-Ame** [comment]
How would I know what you use/where you get them from? Ypu probably added it yourself, check your Yokai Settings >  Browse > Extensions repo page & search up whatever you find in there. They'll probably have their own Discord, support page, and/or GitHub page

Don't share it here, cause it's not affiliated to Yokai & for legal reasons.

**Comment by null2264** [comment]
Please contact the extension maintainer first to get confirmation whether it's an issue with the app or with the extension before creating an issue.
