### ISSUE TITLE
For Local source to detect manga from both internal and external storage, not just one

### ISSUE THREAD

**Issue by lalalasupa0** [null2264/yokai#197]
### Describe your suggested feature

In short, I want my local source to load manga from both my internal and external storage at the same time

### Other details

Currently only one can be chosen, meaning that my local source won't load the manga in one of the two storages, and I would have to move the manga from one to another, but the space in this storage could be full, and that's where the problem arises

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an request for a feature in the original Tachiyomi, I am opening because multiple versions of Yōkai have been released without this feature.
- [X] If this is an issue with an extension, or a request for an extension, I should be contacting the extensions repository's maintainer/support for help.
- [X] I have updated the app to version **[1.8.5.7](https://github.com/null2264/yokai/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [X] I will fill out all of the requested information in this form.

**Comment by null2264** [comment]
Not sure tbh, one of the benefit of one "Storage location" was because some custom rom (especially CN phones and Smasnug) sometime did something that caused the app to lose write access to it (especially for SDCard), so user only have to deal with 1 location to fix. I could probably make the app read from `/sdcard/Android/data/<yokai package id>/local/`, since that location is pretty much free, tho the path is a bit long.

**Comment by lalalasupa0** [comment]
> Not sure tbh, one of the benefit of one "Storage location" was because some custom rom (especially CN phones and Smasnug) sometime did something that caused the app to lose write access to it (especially for SDCard), so user only have to deal with 1 location to fix. I could probably make the app read from `/sdcard/Android/data/<yokai package id>/local/`, since that location is pretty much free, tho the path is a bit long.

Tbf the path you mentioned seems fine to me, what matters, at least to me, is that it detects the manga in my internal and external memory at the same time

**Comment by null2264** [comment]
You can now put local entries on `/storage/sdcard/Android/data/<yokai>/local/files/<entry>` on latest nightly :+1:

**Comment by lalalasupa0** [comment]
> You can now put local entries on `/storage/sdcard/Android/data/<yokai>/local/files/<entry>` on latest nightly (You need to enable it first, Settings > Advanced > Scan external storages for entries) 👍

I see that's great, does it work in both scenarios? Like if my local source is located on my sd card, will the app be able to detect the local source in /data/<yokai> of the internal storage (storage/emulated/0)?

**Comment by null2264** [comment]
It should be able to detect all 3, storage location, emulated/0, and sdcard...

**Comment by lalalasupa0** [comment]
> It should be able to detect all 3, storage location, emulated/0, and sdcard...

Ok ty, this should be closed right?

**Comment by null2264** [comment]
Yep

**Comment by lalalasupa0** [comment]
Does this work for detecting downloads as well? Or is it exclusive for local source? While we're at it I think if possible it would be good to expand the feauture at that too
@null2264

**Comment by null2264** [comment]
It's exclusive for local source at the moment, since I think downloads probably gonna take a lot more time and effort.
