### ISSUE TITLE
Splash screen is broken on Android 12+

### ISSUE THREAD

**Issue by RahmanRagib** [null2264/yokai#20]
### Steps to reproduce

1.open yōkai
2.the starting screen appears

### Expected behavior

Either the logo should appear fullscreen
Or it might not appear 

### Actual behavior

The starting screen logo gets cropped ( about 1/2 of the whole logo)

### Yōkai version

1.7.12

### Android version

Android 13

### Device

Realme 9 4g

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, or a request for an extension, I should be contacting the extensions repository's maintainer/support for help.
- [X] I am reporting an issue exclusive to this fork. I have also checked that is not an issue on the [main version of Mihon](https://github.com/mihonapp/mihon)
- [X] I have tried the [troubleshooting guide](https://mihon.app/help/).
- [X] I have updated the app to version **[1.7.12](https://github.com/null2264/yokai/releases/latest)**.
- [X] I have updated all installed extensions.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I have filled out all of the requested information in this form.

**Comment by null2264** [comment]
You can ignore, just taking some note :v 

Might be worth migrating to new SplashScreen API
REF:
- https://developer.android.com/develop/ui/views/launch/splash-screen
- https://github.com/mihonapp/mihon/commit/05e7b0dc22dbd9d180e3410fdfa8c3fa1759e57d
