### ISSUE TITLE
AsuraScan not working.

### ISSUE THREAD

**Issue by iMoloy** [null2264/yokai#204]
### Steps to reproduce

Asura Scan extension not updating it's manhwa.

### Expected behavior

It should update manhwa.

### Actual behavior

Asura Scan extension not updating it's manhwa.

### Yōkai version

1.8.5.7 stable 

### Android version

Android 14

### Device

Iqoo Z9 5g

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, or a request for an extension, I should be contacting the extensions repository's maintainer/support for help.
- [X] I am reporting an issue exclusive to this fork. I have also checked that is not an issue on the [main version of Mihon](https://github.com/mihonapp/mihon)
- [X] I have tried the [troubleshooting guide](https://mihon.app/help/).
- [X] I have updated the app to version **[1.8.5.7](https://github.com/null2264/yokai/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have filled out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
That's not an app-related issue since it doesn't come with any extensions, go check with whoever maintains your extensions instead.
