### ISSUE TITLE
Hattori Manga: Http error 404

### ISSUE THREAD

**Issue by roseyona** [null2264/yokai#21]
### Steps to reproduce

1.Open Hattori Manga 

### Expected behavior

it should open the manga on the app.

### Actual behavior

But the source doesn't work and it says Http Error 404. 

### Yōkai version

v1.7.12

### Android version

Android 12

### Device

Samsung Galaxy A12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, or a request for an extension, I should be contacting the extensions repository's maintainer/support for help.
- [X] I am reporting an issue exclusive to this fork. I have also checked that is not an issue on the [main version of Mihon](https://github.com/mihonapp/mihon)
- [X] I have tried the [troubleshooting guide](https://mihon.app/help/).
- [X] I have updated the app to version **[1.7.12](https://github.com/null2264/yokai/releases/latest)**.
- [X] I have updated all installed extensions.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I have filled out all of the requested information in this form.

**Comment by null2264** [comment]
Extension issue, please contact the ext repo maintainer instead.
