### ISSUE TITLE
Add library navigation option similar to Mihon

### ISSUE THREAD

**Issue by Cosmicshadows112** [null2264/yokai#216]
### Describe your suggested feature

A similar layout to mihon option, I found the current layout confusing and mihon's intuitive in my opinion. It would be nice being able to switch between them. And possibly add option to copy mihon's navigation bar.

### Other details

Something like:
![Screenshot_20240929_140856_Mihon](https://github.com/user-attachments/assets/66311638-6760-478a-b4b1-f1931582fdbe)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an request for a feature in the original Tachiyomi, I am opening because multiple versions of Yōkai have been released without this feature.
- [X] If this is an issue with an extension, or a request for an extension, I should be contacting the extensions repository's maintainer/support for help.
- [X] I have updated the app to version **[1.8.5.7](https://github.com/null2264/yokai/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [X] I will fill out all of the requested information in this form.

**Comment by null2264** [comment]
Sorry, but no, that'd kill the whole purpose of me forking J2K for its UI. You could however mimic the behaviour of that by going to Settings > Library > Display Options > Categories > Uncheck "Show all categories".
