### ISSUE TITLE
Reset filtered scanlators doesn't work properly

### ISSUE THREAD

**Issue by w00ogly** [null2264/yokai#228]
### Current workaround
Don't use "Reset" button for the time being, unfilter them one by one (painful, I know...), then filter at least one scanlator.

---

### Steps to reproduce

1. Filter scan groups
2. Reset filter
3. Choose chapter from different scan

### Expected behavior

Read chapter like normal

### Actual behavior

![image](https://github.com/user-attachments/assets/32b2b9a7-7b57-42fb-a8aa-342fbd9c335e)
![image](https://github.com/user-attachments/assets/96d0ea71-5675-4b11-8df0-4cd474997a8c)

### Yōkai version

Yokai 1.8.5.9

### Android version

Android 14

### Device

Samsung Galaxy S22 Ultra

### Other details

Already created issue in [REDACTED - Repo name], told me it was an app issue not extension

Same issue found in [REDACTED - Extensions with multi scanlators support]

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, or a request for an extension, I should be contacting the extensions repository's maintainer/support for help.
- [X] I am reporting an issue exclusive to this fork. I have also checked that is not an issue on the [main version of Mihon](https://github.com/mihonapp/mihon)
- [X] I have tried the [troubleshooting guide](https://mihon.app/help/).
- [X] I have updated the app to version **[1.8.5.9](https://github.com/null2264/yokai/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have filled out all of the requested information in this form.

**Comment by null2264** [comment]
Does it work before you filter scanlators?

**Comment by w00ogly** [comment]
Just tried it with vadtd,  it worked after I removed and cleared database but the moment I filtered groups then reset filter I got the same message, so yeah

**Comment by null2264** [comment]
Yeah, the reset button seems to be bugged, I'll redact the extension names. For now the workaround is to not use the reset button to unfilter the scanlator, I'll debug it further when my schedule are free, thanks 👍.

**Comment by w00ogly** [comment]
Just so you know I also did it manually, unfiltered, and got the same error

**Comment by null2264** [comment]
Should be fixed on [v1.8.5.10](https://github.com/null2264/yokai/releases/tag/v1.8.5.10)

**Comment by w00ogly** [comment]
Can confirm seems to be working
