### ISSUE TITLE
Extension Repos backup is not restored

### ISSUE THREAD

**Issue by Hiirbaf** [null2264/yokai#229]
### Steps to reproduce

1. Create a backup
2. Restore the backup to the same or another device
3. Backup works except for the extension repository

### Expected behavior

Extension repositories should be restored

### Actual behavior

They are not restored, they remain blank and must be added manually again.

### Yōkai version

1.8.5.9

### Android version

Android 13

### Device

Samsung A03

### Other details

I tested if it was a problem with all applications that derive from tachiyomi, but in J2K, Mihon, etc. It works fine, only Yokai gives me that problem.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, or a request for an extension, I should be contacting the extensions repository's maintainer/support for help.
- [X] I am reporting an issue exclusive to this fork. I have also checked that is not an issue on the [main version of Mihon](https://github.com/mihonapp/mihon)
- [X] I have tried the [troubleshooting guide](https://mihon.app/help/).
- [X] I have updated the app to version **[1.8.5.9](https://github.com/null2264/yokai/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have filled out all of the requested information in this form.

**Comment by null2264** [comment]
Will be tracked in GH-72.
