### ISSUE TITLE
Please cherry-pick , fix glitch mode longs trip 

### ISSUE THREAD

**Issue by mozzaru** [null2264/yokai#23]
### Steps to reproduce

https://github.com/Saud-97/TachiyomiS97/commit/9eab2bc694a6b76124f08dcf74ca4380606548ed

### Expected behavior

Increased page split height to reduce flickering line issue in Webtoo…
…n reader

### Actual behavior

.

### Crash logs

.

### Yōkai version

1.7.12(yokai)

### Android version

Android 11

### Device

Realme 7i

### Other details

.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, or a request for an extension, I should be contacting the extensions repository's maintainer/support for help.
- [X] I am reporting an issue exclusive to this fork. I have also checked that is not an issue on the [main version of Mihon](https://github.com/mihonapp/mihon)
- [X] I have tried the [troubleshooting guide](https://mihon.app/help/).
- [X] I have updated the app to version **[1.7.12](https://github.com/null2264/yokai/releases/latest)**.
- [X] I have updated all installed extensions.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I have filled out all of the requested information in this form.

**Comment by null2264** [comment]
I'm a bit hesitant to do this due to the maintainer's bad rep, but what could possibly go wrong eh? It's just one line of code anyway...
