### ISSUE TITLE
Kitsu login unknown error

### ISSUE THREAD

**Issue by advait404** [null2264/yokai#231]
I am trying to login to kitsu after I logged out when recieving some 403 like errors. However login attempts give a unknown error message.

I tried to login using another mihon fork, and was able to make it work without issues.

**Comment by null2264** [comment]
Invalid issue format should've used one of the issue template, but I'll let it slide this time, could you please provide the version you're using? (Triple dots > About > Tap version, paste it here)

**Comment by advait404** [comment]
The app version is 1.8.5.9

Sorry about not using the issue template. I am using a github android client and it probably does not support templates.

**Comment by null2264** [comment]
Probably an issue on Kitsu side then...
