### ISSUE TITLE
Yokai is extremely Slow on showing manga chapters available in Local source

### ISSUE THREAD

**Issue by theRedKitty** [null2264/yokai#236]
### Steps to reproduce

1.Put manga inside the Local directory for reading
2.Go to Local under the browse section of the app
3.Add that Local manga
4.Open said manga

Issue here is that it takes some seconds(5 or more) depending on the size of the manga to show the list of chapters available. The app momentarily shows a blank page as if trying to load something. Even when the chapters load and are shown, when you exit the app and go back to that local manga the issue persists even when you've already opened the manga before. It's extremely annoying and time consuming waiting for it to load local chapters which it doesn't do on the downloaded ones no matter how many they are. 
![Screenshot_20241104-094146](https://github.com/user-attachments/assets/ba3cec15-8c20-4dee-9ebf-b25336bd25d5)
![Screenshot_20241104-094124](https://github.com/user-attachments/assets/081d91d2-7f61-4dc8-86cd-178da1fe354c)
![Screenshot_20241104-094138](https://github.com/user-attachments/assets/f0f43b0d-c233-4697-bddd-6a0a188120c8)

### Expected behavior

The app should instantly she the local chapters available
![Screenshot_20241104-094138](https://github.com/user-attachments/assets/6c6e01f9-ada7-4545-ba6c-7bd7c5424163)

### Actual behavior

The app take its time (5+ seconds) just to show the list of chapters available locally and even shows a blank page for some time.

![Screenshot_20241104-094124](https://github.com/user-attachments/assets/7eb35a46-0ddb-41c6-b149-fa6e6012881d)

### Yōkai version

1.8.5.9

### Android version

Android 12

### Device

itel S662L

### Other details

I don't know if it helps but I've resorted to using j2k 1.7.4 and the main mihon app as they don't show such a problem. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, or a request for an extension, I should be contacting the extensions repository's maintainer/support for help.
- [X] I am reporting an issue exclusive to this fork. I have also checked that is not an issue on the [main version of Mihon](https://github.com/mihonapp/mihon)
- [X] I have tried the [troubleshooting guide](https://mihon.app/help/).
- [X] I have updated the app to version **[1.8.5.9](https://github.com/null2264/yokai/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have filled out all of the requested information in this form.

**Comment by null2264** [comment]
It's a J2K behaviour to refresh local source entries everytime you open it, I'll change it so that it'll load first before refreshing when my schedule is free 👍

**Comment by null2264** [comment]
It's now behaves like online source on latest nightly (commit: https://github.com/null2264/yokai/commit/2dfc1e3451804636a8e15c96eee0481c113d4fee)
