### ISSUE TITLE
Kitsu tracker: HTTP error 401

### ISSUE THREAD

**Issue by C0untD0wn777** [null2264/yokai#238]
### Steps to reproduce

When I read something, it should mark it as read, but I get an error and it doesn't track it. Website works, but not on Yokai.

### Expected behavior

It should track where I'm at when a chapter is completed.
![Screenshot_20241110_181946_Ykai](https://github.com/user-attachments/assets/b716e78f-9fda-428d-af83-8b23a204105b)

### Actual behavior

It gives an error and it doesn't track. 
![Screenshot_20241110_181930_Ykai](https://github.com/user-attachments/assets/5318ed42-61f4-4e37-8e4f-5ed59b3091dc)

### Yōkai version

1.8.5.9

### Android version

Android 13

### Device

Samsung galaxy S22+

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, or a request for an extension, I should be contacting the extensions repository's maintainer/support for help.
- [X] I am reporting an issue exclusive to this fork. I have also checked that is not an issue on the [main version of Mihon](https://github.com/mihonapp/mihon)
- [X] I have tried the [troubleshooting guide](https://mihon.app/help/).
- [X] I have updated the app to version **[1.8.5.9](https://github.com/null2264/yokai/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have filled out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
401 means you need to refresh your login, you can try to unlink & relink your AniList in the app's Trackerror page.

However, AniList has been experiencing some issues recently & have disabled/have unstable API currently. Check AniList for more info/issues, and/or come to the Mihon Discord yokai-j2k channel for basic issues/troubleshooting (in general).

**Comment by C0untD0wn777** [comment]
Thank you very much. It worked.
