### ISSUE TITLE
create backup with just history information

### ISSUE THREAD

**Issue by xdeiimoss** [null2264/yokai#243]
### Describe your suggested feature

Would it be possible to make this? I'm not sure how to explain this more than the title is doing
Basically, I just need the history on the backup sometimes. Would it be possible to make something like this?

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an request for a feature in the original Tachiyomi, I am opening because multiple versions of Yōkai have been released without this feature.
- [X] If this is an issue with an extension, or a request for an extension, I should be contacting the extensions repository's maintainer/support for help.
- [X] I have updated the app to version **[1.8.5.9](https://github.com/null2264/yokai/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [X] I will fill out all of the requested information in this form.

**Comment by null2264** [comment]
Already possible, just untick everything except for history. If you're asking for literal "just history" where you also exclude entries, unfortunately that's not possible, the history is tied to chapters which tied to those entries.
