### ISSUE TITLE
The new splash screen lasts longer than it should

### ISSUE THREAD

**Issue by mechagomizilla** [null2264/yokai#26]
### Steps to reproduce

1. Set Library as the screen to display at launch
2. Make sure that Yōkai is closed
3. Launch Yōkai

### Expected behavior

The splash screen should last around 2 seconds, maybe less or more depending on the phone's performance.

### Actual behavior

I counted around 6 seconds before the splash screen disappears since the update to 1.7.13. It doesn't shorten on subsequent launches.

### Yōkai version

1.7.13

### Android version

Android 14

### Device

Samsung Galaxy S23 Ultra

### Other details

I definitely did not have this issue right before updating.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, or a request for an extension, I should be contacting the extensions repository's maintainer/support for help.
- [X] I am reporting an issue exclusive to this fork. I have also checked that is not an issue on the [main version of Mihon](https://github.com/mihonapp/mihon)
- [X] I have tried the [troubleshooting guide](https://mihon.app/help/).
- [X] I have updated the app to version **[1.7.13](https://github.com/null2264/yokai/releases/latest)**.
- [X] I have updated all installed extensions.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I have filled out all of the requested information in this form.

**Comment by null2264** [comment]
It supposed to wait for library/recents/browser page to be loaded fully or 5 seconds in case it takes too long to load. But I'll take a look if I could make it faster.

**Comment by mechagomizilla** [comment]
I guess the extra 6th second is for the launch animation then.

Thanks to your reply, I was able to confirm that in fact, the app loads faster when recents or browse are set as the screen to show at startup. It takes just over 1 second. Maybe just loading what is actually visible on screen should be enough for the library. If it's not possible to determine, then maybe just loading the first visible category.

Btw, I only have a few dozen titles, so it's really not a quantity problem. I'm not a hoarder.
