### ISSUE TITLE
When using the Tracking feature, the app crashes after finishing a chapter of certain manga.

### ISSUE THREAD

**Issue by poliexz** [null2264/yokai#262]
### Steps to reproduce

1. About to finish a chapter of a manga.
2. The app crashes when transitioning to the next chapter.

### Expected behavior

1. Mark a manga chapter as read.
2. Track my reading progress.

### Actual behavior

The app crashes after finishing reading, and the tracking is not completed.

### Crash logs

App version: 1.8.5.10 (standard, 57fe8e8ae3, 149, 2024-11-19T01:39:44Z) Android version: 14 (SDK 34) Android build ID: KB2000_14.0.0.602(CN01) Device brand: OnePlus Device manufacturer: OnePlus Device name: OnePlus8T Device model: KB2000 Device product name: OnePlus8T_CH java.lang.Throwable: kotlin.NotImplementedError: Unknown status: 0 	at eu.kanade.tachiyomi.data.track.bangumi.BangumiModelsKt.toBangumiStatus(SourceFile:40) 	at eu.kanade.tachiyomi.data.track.bangumi.BangumiApi$updateLibManga$2.invokeSuspend(SourceFile:58) 	at eu.kanade.tachiyomi.data.track.bangumi.BangumiApi$updateLibManga$2.invoke(SourceFile:13) 	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(SourceFile:19) 	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(SourceFile:52) 	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:0) 	at eu.kanade.tachiyomi.data.track.bangumi.Bangumi.update(SourceFile:21) 	at eu.kanade.tachiyomi.util.chapter.ChapterTrackSyncKt.updateTrackChapterRead(SourceFile:256) 	at eu.kanade.tachiyomi.ui.reader.ReaderViewModel$updateTrackChapterAfterReading$1.invokeSuspend(SourceFile:64) 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(SourceFile:12) 	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:92) 	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(SourceFile:4) 	at kotlinx.coroutines.scheduling.TaskImpl.run(Unknown Source:2) 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(SourceFile:1) 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(SourceFile:63) 	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@9b51c18, Dispatchers.IO] --------- beginning of main 11-23 06:51:53.646 6024 6257 E OpenGLRenderer: Unable to match the desired swap behavior. 11-23 06:52:01.902 6024 6024 E RippleDrawable: The RippleDrawable.STYLE_PATTERNED animation is not supported for a non-hardware accelerated Canvas. Skipping animation. 11-23 06:52:01.905 6024 6257 E FrameEvents: updateAcquireFence: Did not find frame. 11-23 06:52:02.004 6024 6024 E OplusBracketLog: [OplusViewMirrorManager] updateHostViewRootIfNeeded, not support android.view.ViewRootImpl@bde2df 11-23 06:52:02.027 6024 6257 E OpenGLRenderer: Unable to match the desired swap behavior. 11-23 06:52:08.299 6024 6182 E : Something went wrong! 11-23 06:52:08.299 6024 6182 E : kotlin.NotImplementedError: Unknown status: 0 11-23 06:52:08.299 6024 6182 E : 	at eu.kanade.tachiyomi.data.track.bangumi.BangumiModelsKt.toBangumiStatus(SourceFile:40) 11-23 06:52:08.299 6024 6182 E : 	at eu.kanade.tachiyomi.data.track.bangumi.BangumiApi$updateLibManga$2.invokeSuspend(SourceFile:58) 11-23 06:52:08.299 6024 6182 E : 	at eu.kanade.tachiyomi.data.track.bangumi.BangumiApi$updateLibManga$2.invoke(SourceFile:13) 11-23 06:52:08.299 6024 6182 E : 	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(SourceFile:19) 11-23 06:52:08.299 6024 6182 E : 	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(SourceFile:52) 11-23 06:52:08.299 6024 6182 E : 	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:0) 11-23 06:52:08.299 6024 6182 E : 	at eu.kanade.tachiyomi.data.track.bangumi.Bangumi.update(SourceFile:21) 11-23 06:52:08.299 6024 6182 E : 	at eu.kanade.tachiyomi.util.chapter.ChapterTrackSyncKt.updateTrackChapterRead(SourceFile:256) 11-23 06:52:08.299 6024 6182 E : 	at eu.kanade.tachiyomi.ui.reader.ReaderViewModel$updateTrackChapterAfterReading$1.invokeSuspend(SourceFile:64) 11-23 06:52:08.299 6024 6182 E : 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(SourceFile:12) 11-23 06:52:08.299 6024 6182 E : 	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:92) 11-23 06:52:08.299 6024 6182 E : 	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(SourceFile:4) 11-23 06:52:08.299 6024 6182 E : 	at kotlinx.coroutines.scheduling.TaskImpl.run(Unknown Source:2) 11-23 06:52:08.299 6024 6182 E : 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(SourceFile:1) 11-23 06:52:08.299 6024 6182 E : 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(SourceFile:63) 11-23 06:52:08.299 6024 6182 E : 	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@9b51c18, Dispatchers.IO] 11-23 06:52:08.422 9327 9327 E OplusBracketLog: [OplusViewMirrorManager] updateHostViewRootIfNeeded, not support android.view.ViewRootImpl@57e611a 11-23 06:52:08.471 9327 9388 E OpenGLRenderer: Unable to match the desired swap behavior. 11-23 06:52:09.319 8285 8285 E tachiyomi.yokai: Unknown bits set in runtime_flags: 0x40000000 11-23 06:52:09.322 8285 8285 E tachiyomi.yokai: Not starting debugger since process cannot load the jdwp agent. 11-23 06:52:09.421 8285 8285 E SchedAssist: sysOpen failed with error=Permission denied 11-23 06:52:09.421 8285 8285 E SchedAssist: sharedImFd failed with error=Permission denied 11-23 06:52:09.472 8285 8338 E tachiyomi.yokai: No package ID 76 found for resource ID 0x760b000f. 11-23 06:52:09.473 8285 8338 E tachiyomi.yokai: No package ID 76 found for resource ID 0x760b000f. 11-23 06:52:09.491 8285 8344 E chromium: [1123/065209.490739:ERROR:variations_seed_loader.cc(39)] Seed missing signature.

### Yōkai version

1.8.5.10

### Android version

Android 14

### Device

OnePlus 8T

### Other details

1.It seems that the issue no longer occurs after disabling "Update tracking after reading."
2. It seems that not all manga experience this issue.
3. The tracking website I use is Bangumi, and there might be an issue with the API.
4. The issue can be reproduced in a Extensions named "DMZJ," where there is a manga called "和歌酱今天也很腹黑."

5. The video at "https://github.com/user-attachments/assets/b71fa98a-7484-4399-8151-d66df1fd0d19" can demonstrate the process of reproducing the issue.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, or a request for an extension, I should be contacting the extensions repository's maintainer/support for help.
- [X] I am reporting an issue exclusive to this fork. I have also checked that is not an issue on the [main version of Mihon](https://github.com/mihonapp/mihon)
- [X] I have tried the [troubleshooting guide](https://mihon.app/help/).
- [X] I have updated the app to version **[1.8.5.10](https://github.com/null2264/yokai/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have filled out all of the requested information in this form.

**Comment by null2264** [comment]
Will be fixed in v1.8.5.11 ([branch `fix/bangumi-status-zero`](https://github.com/null2264/yokai/tree/fix/bangumi-status-zero))
