### ISSUE TITLE
Extension 

### ISSUE THREAD

**Issue by Allphonso** [null2264/yokai#265]
### Steps to reproduce

Manganato extension seems to broke in the app..but in manganato website it just fine 
![Screenshot_2024-11-15-08-37-10-42](https://github.com/user-attachments/assets/cef30b50-a3d2-4258-a250-c0502864b61e)

### Expected behavior

Working 

### Actual behavior

Not loading picture 

### Yōkai version

New version 

### Android version

14

### Device

Realme c3

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, or a request for an extension, I should be contacting the extensions repository's maintainer/support for help.
- [X] I am reporting an issue exclusive to this fork. I have also checked that is not an issue on the [main version of Mihon](https://github.com/mihonapp/mihon)
- [X] I have tried the [troubleshooting guide](https://mihon.app/help/).
- [X] I have updated the app to version **[1.8.5.12](https://github.com/null2264/yokai/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have filled out all of the requested information in this form.

**Comment by null2264** [comment]
Please confirm that it's in fact an issue with the app with the extension maintainer before reporting a bug regarding extension, this is not where you report extension issues as Yokai is not associated with any extensions.
