### ISSUE TITLE
'HTTP error 404' whilst downloading

### ISSUE THREAD

**Issue by lalalasupa0** [null2264/yokai#266]
### Steps to reproduce

Open Kemono extension
Open artist page Vadass
Start downloading chapter `Special Guest Ryouko from Mokuzou Zabuton` (NSWF)

### Expected behavior

Should download it like the others from the same entry

### Actual behavior

Stopped download and notification `HTTP error 404`

### Yōkai version

App version: 1.8.5.12-r5851 (standard, 7df619ac13, 149, 2024-11-25T07:51:35Z) Android version: 11 (SDK 30) Android build ID: RPNS31.Q1-51-40-16-12 Device brand: motorola Device manufacturer: motorola Device name: nairo Device model: motorola one 5G Device product name: nairo_a

### Android version

Android 11

### Device

Moto One 5G

### Other details

I also got some internal server error thing but it got overwritted by the HTTP error 404 before I could check

Idk if this really is an issue from the app and not the extension

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, or a request for an extension, I should be contacting the extensions repository's maintainer/support for help.
- [X] I am reporting an issue exclusive to this fork. I have also checked that is not an issue on the [main version of Mihon](https://github.com/mihonapp/mihon)
- [X] I have tried the [troubleshooting guide](https://mihon.app/help/).
- [X] I have updated the app to version **[1.8.5.12](https://github.com/null2264/yokai/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have filled out all of the requested information in this form.

**Comment by null2264** [comment]
Seems to be source problem, posts in that site sometimes went \*poof\* every now and then, since you got internal server error I'm guessing the post got nuked due to the site's server crashed or something... Not an app issue.
