### ISSUE TITLE
[Bug] Attempting to restore a backup file from Mihon, crashed with a "Permission Denial"/"NullPointerException"

### ISSUE THREAD

**Issue by infyProductions** [null2264/yokai#267]
### Steps to reproduce

1. Create backup file (with the usual defaults of: `Library entries, Chapters, Tracking, History, Categories, All read entries, App settings, Extension repos, Source settings`) in Mihon (using r7015)
![image](https://github.com/user-attachments/assets/65e7b680-2b53-4bd8-a388-e569f34b5b50)
2. On Yokai, do the usual restore procedure and select the file from the file picker (I picked the one from my Downloads folder since I usually upload my backups to the cloud).
![image](https://github.com/user-attachments/assets/327e8615-2b0a-493f-83ce-b602079d17af)
3. Tap the Restore button when prompted
![image](https://github.com/user-attachments/assets/7c382606-731d-4a6b-83c0-df3d2bc89c61)
4. Wait until either it will succeed or crash in utter failure

### Expected behavior

Restoration process should complete without any crashing

### Actual behavior

Upon clicking restore and waited around a minute in real life (made it onto a timelapse to make it fit due to size constraints of the original screen capture), it crashed with `NullPointerException` on the crash screen with a notification saying `Permission Denial: reading com.android.externalstorage.ExternalStorageProvider uri content://...`

https://github.com/user-attachments/assets/8a7b0bf9-32ba-48bf-abc3-844dadaadbc5

![image](https://github.com/user-attachments/assets/12bb90d9-9a12-4818-b5ac-b0b0a83e87e5)

### Crash logs

Here's the crash log as an attachment
[yokai_crash_logs_11-26-2024.txt](https://github.com/user-attachments/files/17914031/yokai_crash_logs_11-26-2024.txt)

### Yōkai version

1.8.5.12

### Android version

Android 13

### Device

Windows Subsystem for Android 2407.40000.0.0

### Other details

I just did an update to the latest version (which is 1.8.5.12). From what I experienced with `permission denial` notification errors (at least on Mihon) are usually when I restore the file from cloud storage (like Google Drive); I just opened Google Drive and kept on the background while I'll restore the backup file from a specific directory on there.

This time, even creating a local backup (downloading the backup file), it still errors out.

I tried a test restore with the backup containing: `Library entries, Chapters, Tracking, History, Categories, All read entries` but it seems to work (finally beyond 1%) and even restored it successfully (even with the tracker warning)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, or a request for an extension, I should be contacting the extensions repository's maintainer/support for help.
- [X] I am reporting an issue exclusive to this fork. I have also checked that is not an issue on the [main version of Mihon](https://github.com/mihonapp/mihon)
- [X] I have tried the [troubleshooting guide](https://mihon.app/help/).
- [X] I have updated the app to version **[1.8.5.12](https://github.com/null2264/yokai/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have filled out all of the requested information in this form.

**Comment by null2264** [comment]
Can you move the backup outside of Downloads folder and retry? Iirc modern Android doesn't like other apps accessing Downloads folder...

**Comment by infyProductions** [comment]
It's the next day for me. Moving the backup file to a different directory worked (I used `/storage/emulated/0/Yokai` folder)
![image](https://github.com/user-attachments/assets/e0e9755b-929b-4d15-9863-f9546e4b182b)
I'm guessing it has to do with SAF or a different reason?

**Comment by null2264** [comment]
Yeah, iirc in Android 12, Google decided to block off Download folder entirely... Well iirc it's not exactly fully blocked, an app just can't interact with files that created/modified by other apps or something...

**Comment by null2264** [comment]
I'll close this issue since it's Android limitation issue, can't do anything about it...

**Comment by infyProductions** [comment]
Finally I narrow it down as to why it crashed. I have bizarre thing about my database contained in the backup is messed up somehow since I manually sync my library between multiple devices. The "fix" is clearing the database and attempt the restore again.
