### ISSUE TITLE
Language missing

### ISSUE THREAD

**Issue by NeKoOuO** [null2264/yokai#269]
### Steps to reproduce

Traditional Chinese missing in language option.
But it doesn't have any change here
[i18n/src/commonMain/moko-resources/zh-rTW
](https://github.com/null2264/yokai/tree/master/i18n/src/commonMain/moko-resources/zh-rTW)I don't know why

### Expected behavior

It should have traditional Chinese option

### Actual behavior

Traditional Chinese missing

### Yōkai version

1.8.5.12

### Android version

Android 13

### Device

Mi 10 ultra 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, or a request for an extension, I should be contacting the extensions repository's maintainer/support for help.
- [X] I am reporting an issue exclusive to this fork. I have also checked that is not an issue on the [main version of Mihon](https://github.com/mihonapp/mihon)
- [X] I have tried the [troubleshooting guide](https://mihon.app/help/).
- [X] I have updated the app to version **[1.8.5.12](https://github.com/null2264/yokai/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have filled out all of the requested information in this form.

**Comment by null2264** [comment]
Fixed on latest nightly (commit https://github.com/null2264/yokai/commit/65682bb5bdf91681048fc9fe725240c058263ec4)
