### ISSUE TITLE
The default folder name for Yōkai causes issues

### ISSUE THREAD

**Issue by mechagomizilla** [null2264/yokai#27]
### Steps to reproduce

1. Use a file browser that doesn't support certain special characters like "ō", i.e.: Samsung's "My Files"
2. Try to transfer files out of or into it
3. Get an error message

### Expected behavior

This wouldn't happen if the folder's name was only using basic Latin characters. I had to rename the folder to Yokai to avoid issues with transfering files.

### Actual behavior

Having Yōkai as the default folder name can prevent new users from successfully migrating their files if they intend to switch phones or transfer them to another folder.

### Yōkai version

1.7.13

### Android version

Android 14

### Device

Samsung Galaxy S23 Ultra

### Other details

Only using basic Latin characters is actually standard practice for file systems to avoid compatibility issues.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, or a request for an extension, I should be contacting the extensions repository's maintainer/support for help.
- [X] I am reporting an issue exclusive to this fork. I have also checked that is not an issue on the [main version of Mihon](https://github.com/mihonapp/mihon)
- [X] I have tried the [troubleshooting guide](https://mihon.app/help/).
- [X] I have updated the app to version **[1.7.13](https://github.com/null2264/yokai/releases/latest)**.
- [X] I have updated all installed extensions.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I have filled out all of the requested information in this form.

**Comment by RahmanRagib** [comment]
I think keeping the characters in casual English might be better it looks a bit glitchy in my app drawer too
Device : Realme 9 4g
Android: 13
