### ISSUE TITLE
Download Cache Deadlock/Long Processing

### ISSUE THREAD

**Issue by Neuron5078** [null2264/yokai#277]
### Steps to reproduce

Read for over an hour until cache renews and you hit chapter deletion at the same time.

### Expected behavior

Cache should handle attempted concurrent access from main thread. Cache should likely be reworked to implement coroutine Mutex since coroutines can follow this code path and end up running runBlocking inside of another coroutine which should be avoided as it will block the entire thread.

### Actual behavior

Deadlock happens long enough for ANR to kick in which causes app to have to be killed to start reading again. While perhaps not a true deadlock the runBlocking blocks the main thread long enough waiting for a lock on the cache, or blocking while running the cache renew that the UI freezes.

### Yōkai version

v1.9.0-b3

### Android version

Android 15

### Device

Google Pixel 8 Pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, or a request for an extension, I should be contacting the extensions repository's maintainer/support for help.
- [X] I am reporting an issue exclusive to this fork. I have also checked that is not an issue on the [main version of Mihon](https://github.com/mihonapp/mihon)
- [X] I have tried the [troubleshooting guide](https://mihon.app/help/).
- [X] I have updated the app to version **[1.8.5.13](https://github.com/null2264/yokai/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have filled out all of the requested information in this form.

**Comment by Neuron5078** [comment]
Specifically `@Synchronized` combined with this line https://github.com/null2264/yokai/blob/332f3f7ee6ffec42c6688d47f70afc8e7de2359c/app/src/main/java/eu/kanade/tachiyomi/data/download/DownloadCache.kt#L136

I believe is the issue.

**Comment by null2264** [comment]
Try [Beta 5](https://github.com/null2264/yokai/releases/tag/v1.9.0-b5)

**Comment by Neuron5078** [comment]
So far it appears that this has solved the deadlocking. Will reopen if it comes back with same issue. Thanks!
