### ISSUE TITLE
Inquiry or proposal. 🩵🌷

### ISSUE THREAD

**Issue by Alex17273747576777** [null2264/yokai#288]
### Describe your suggested feature

I propose, on the hypothesis that it is not yet incorporated into the application, the establishment of an automatic genre generator for the library. This system should have the capability to analyze the existing content and allow for the application of filters comparable to an intelligent update of the repertoire. The mentioned functionality should ask the user about the number of genres they would like to generate and present the results for further review. Additionally, it would be advantageous to have an automatic organizer. Although it might seem complex, an illustrative example could be Smart Launcher 6, version 2. I acknowledge that they are different applications, but I mention it to provide a concrete reference. I recommend implementing it separately to avoid device failures and, if feasible, offering a warning regarding background resource consumption, depending on the size of the library's collection.

### Other details

My apologies for the lengthy response; and using AI, I'm sorry I can't articulate my thoughts more clearly. 😔🌹

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an request for a feature in the original Tachiyomi, I am opening because multiple versions of Yōkai have been released without this feature.
- [X] If this is an issue with an extension, or a request for an extension, I should be contacting the extensions repository's maintainer/support for help.
- [X] I have updated the app to version **[1.9.0](https://github.com/null2264/yokai/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Why not search the tag/"genre" you want in your Library search bar? See first two pictures

Otherwise, what about the Library group setting, where you can group by tag (see third picture)

![Screenshot_20241210_094507_Ykai.png](https://github.com/user-attachments/assets/b86c3187-8526-47b6-8084-619de48713a3)

![Screenshot_20241210_094520_Ykai.png](https://github.com/user-attachments/assets/b4ce32e2-c722-4abd-8125-3b6b55c655ba)

![Screenshot_20241210_094450_Ykai.png](https://github.com/user-attachments/assets/861a6863-cb9b-4cf0-b827-d365be4e66fd)

**Comment by Alex17273747576777** [comment]
I appreciate the information, I was not aware that I had that. :3

**Comment by null2264** [comment]
Closing this since similar feature already exists, "Group by tag".
