### ISSUE TITLE
Reduce the empty space in the upper part of library 

### ISSUE THREAD

**Issue by MrDfour** [null2264/yokai#29]
### Describe your suggested feature

The empty space in the upper row is too big. I'm unsure if it a bug or a design choosing but it takes almost one third of the screen space
![Screenshot_20240210-121615_Yōkai](https://github.com/null2264/yokai/assets/103494853/6879ae53-3505-44dc-bdfd-47c4d5e44741)

### Other details

If its in the wrong place or there's a way to fix it, I'm sorry but couldn't find it nor know where to actually place the issue 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an request for a feature in the original Tachiyomi, I am opening because multiple versions of Yōkai have been released without this feature.
- [X] If this is an issue with an extension, or a request for an extension, I should be contacting the extensions repository's maintainer/support for help.
- [X] I have updated the app to version **[1.7.13](https://github.com/null2264/yokai/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by null2264** [comment]
It is by design, you can disable it by going to settings, appearance, disable expanded toolbar.

This is the same design as Android 13, to make it easier to reach searchbox one handed.
