### ISSUE TITLE
Every time I go to read a new chapter the app restarts 

### ISSUE THREAD

**Issue by sworkwef** [null2264/yokai#290]
### Steps to reproduce

I enter the app, there is a new chapter or one I haven't read, when it is loading the app restarts

### Expected behavior

should load the pages

### Actual behavior

The pages do not load and the app restarts

### Yōkai version

1.9.0

### Android version

android 9

### Device

asus zenfone max pro m2

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, or a request for an extension, I should be contacting the extensions repository's maintainer/support for help.
- [X] I am reporting an issue exclusive to this fork. I have also checked that is not an issue on the [main version of Mihon](https://github.com/mihonapp/mihon)
- [X] I have tried the [troubleshooting guide](https://mihon.app/help/).
- [X] I have updated the app to version **[1.9.0](https://github.com/null2264/yokai/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have filled out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Most recent update can mean two different versions, and what if you aren't receiving updates? Actually check & write the version number

**Comment by sworkwef** [comment]
It is version 1.9.0

**Comment by Smol-Ame** [comment]
Check WebView (or in your own browser) to see if there's any issues with the chapter's pages (missing, broken, etc)

**Comment by null2264** [comment]
Also, is it a webtoon/long strip or is it a manga?

**Comment by null2264** [comment]
When that happened again, head to Settings -> Advanced -> Dump crash logs, then send the logs here for more context...

**Comment by null2264** [comment]
Try [1.9.1 Beta 1](https://github.com/null2264/yokai/releases/tag/v1.9.1-b1)

**Comment by sworkwef** [comment]
Thank you very much, the problem has been solved
