### ISSUE TITLE
Slow Chapter Load

### ISSUE THREAD

**Issue by Recri97** [null2264/yokai#292]
### Steps to reproduce

Search title that has many chapter in my case Nobless(600+ chapter)

### Expected behavior

Should load immediately 

### Actual behavior

It takes around 1min+ to load

### Yōkai version

1.9.1

### Android version

Android 11

### Device

Redmi Note 8

### Other details

It only slow for the first time load after that it load normaly

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, or a request for an extension, I should be contacting the extensions repository's maintainer/support for help.
- [X] I am reporting an issue exclusive to this fork. I have also checked that is not an issue on the [main version of Mihon](https://github.com/mihonapp/mihon)
- [X] I have tried the [troubleshooting guide](https://mihon.app/help/).
- [X] I have updated the app to version **[1.9.1](https://github.com/null2264/yokai/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have filled out all of the requested information in this form.

**Comment by null2264** [comment]
I think this is depends on the source... I load an entry with 3000 chapters pretty fast, doesn't even take longer than 30 sec...

**Comment by Recri97** [comment]
> I think this is depends on the source... I load an entry with 3000 chapters pretty fast, doesn't even take longer than 30 sec...

Tried different source still same , but when I try load 5000 chapter with Komikku it load instantly

**Comment by null2264** [comment]
I might know the reason, I'll debug further later...

**Comment by null2264** [comment]
Should be fixed on latest nightly (commit: https://github.com/null2264/yokai/commit/ea0496858144b3ede830aec640ca6b669c3ec158)

**Comment by Recri97** [comment]
> Should be fixed on latest nightly (commit: [ea04968](https://github.com/null2264/yokai/commit/ea0496858144b3ede830aec640ca6b669c3ec158))

Thanks , it fixed now
