### ISSUE TITLE
messy sort vol&chapter

### ISSUE THREAD

**Issue by RicheMeier** [null2264/yokai#294]
### Steps to reproduce

![Screenshot_20241211-011211](https://github.com/user-attachments/assets/30d386e1-eea6-42d8-a445-fac574c01917)

### Expected behavior

sort by chapter number setting, sort volume 1 first and volume 2 later.

### Actual behavior

sort by chapter number setting, it's messy.

vol 1 chapter 1
vol 2 chapter 1
vol 1 chapter 2
vol 2 chapter 2
.
.
.

Sort by chapter first, then by volume.

### Yōkai version

1.8.0

### Android version

Android 12

### Device

Samsung A90, etc

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, or a request for an extension, I should be contacting the extensions repository's maintainer/support for help.
- [ ] I am reporting an issue exclusive to this fork. I have also checked that is not an issue on the [main version of Mihon](https://github.com/mihonapp/mihon)
- [X] I have tried the [troubleshooting guide](https://mihon.app/help/).
- [X] I have updated the app to version **[1.9.1](https://github.com/null2264/yokai/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have filled out all of the requested information in this form.

**Comment by null2264** [comment]
Work as intended, Yokai doesn't support volume.
