### ISSUE TITLE
Read chapters not deleting automatically

### ISSUE THREAD

**Issue by MrDfour** [null2264/yokai#295]
### Steps to reproduce

When read the chapters don't self delete. I tried to deactivate and reactivate the option but it didn't work, you have to manually delete them.

### Expected behavior

Chapter should delete automatically 

### Actual behavior

It needs manual deletion 

### Yōkai version

1.9.2

### Android version

Android 14

### Device

Poco X6 Pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, or a request for an extension, I should be contacting the extensions repository's maintainer/support for help.
- [X] I am reporting an issue exclusive to this fork. I have also checked that is not an issue on the [main version of Mihon](https://github.com/mihonapp/mihon)
- [X] I have tried the [troubleshooting guide](https://mihon.app/help/).
- [X] I have updated the app to version **[1.9.2](https://github.com/null2264/yokai/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have filled out all of the requested information in this form.

**Comment by null2264** [comment]
Can you double check that you're indeed using the latest version? Settings -> About -> Version, then paste it here.

**Comment by MrDfour** [comment]
Sorry for the delay, got caught up in stuff. I was using the last update but I discovered it was getting deleted, just way slower than how it used to be. I don't know, although I don't think so, if it's related to my dveicr performance but since it works I don't think this is an issue

**Comment by null2264** [comment]
It's probably not showing that it's already been deleted even tho it's already is...
