### ISSUE TITLE
Manganato extension 

### ISSUE THREAD

**Issue by Allphonso** [null2264/yokai#297]
### Steps to reproduce

Not loading picture of the m/m/m but on website it works perfectly 

### Expected behavior

Working normally 

### Actual behavior

Manganato extension seems not working and no fix, come on i don't like use others extension 

### Yōkai version

New version 

### Android version

14

### Device

Realme c3

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, or a request for an extension, I should be contacting the extensions repository's maintainer/support for help.
- [X] I am reporting an issue exclusive to this fork. I have also checked that is not an issue on the [main version of Mihon](https://github.com/mihonapp/mihon)
- [X] I have tried the [troubleshooting guide](https://mihon.app/help/).
- [X] I have updated the app to version **[1.9.2](https://github.com/null2264/yokai/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have filled out all of the requested information in this form.

**Comment by null2264** [comment]
Talk to whoever maintain that extension and confirm that it's an app issue before opening an issue. There are no extensions associated with Yokai, never has, never will.

**Comment by Allphonso** [comment]
How to talk or contact them though? because I thought you guys were the one maintaining the extension

**Comment by null2264** [comment]
Head to Source > Extensions > Find the extension > Settings > Find this button, it should redirect you to the repo. Other than that you're on your own.

![Screenshot_2024_1212_135214.png](https://github.com/user-attachments/assets/f21b35e1-aa85-41dc-a01b-f784f82fa6d5)
