### ISSUE TITLE
Local Source not detected

### ISSUE THREAD

**Issue by CBozsik** [null2264/yokai#3]
### Steps to reproduce

I'm not sure of the local source functionality is working. I'm transitioning over from TachiJ2K where I have a series in TachiyomiJ2K/local folder that works fine.

I have tried:
- Yokai/local
- Tachiyomi/local
- TachiyomiJ2K/local
- Manga/local (since I've moved downloads and backups into a Manga directory instead of app-specific names after moving over).

I briefly played with TachiyomiSY which is more up to date with the last mainline Tachiyomi release and it seemed to have simplified the settings for choosing what directory everything goes into so that would be nice to see eventually.

### Expected behavior

Files should be detected from a local folder _somewhere_, I just can't figure out where this folder should be.

### Actual behavior

Nothing.
I do see the cover art of the series when I leave it in the original TachiyomiJ2K/local folder, but none of the files load. I figure this might be a side effect of importing my backup from J2K.

### Yōkai version

1.7.7

### Android version

Android 14

### Device

Galaxy S23 Ultra

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I am reporting an issue exclusive to this fork. I have also checked that is not an issue on the [main version of Tachiyomi](https://github.com/tachiyomiorg/tachiyomi)
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.7.7](https://github.com/null2264/yokai/releases/latest)**.
- [X] I have updated all installed extensions.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I have filled out all of the requested information in this form.

**Comment by null2264** [comment]
It should now detect non stylized `Yokai/` and `TachiyomiJ2K/` folder (v1.7.8)

**Comment by CBozsik** [comment]
Just updated and checked both folder names work correctly, thanks!

I guess based on the "what's new" nite it was expecting the folder to be called Yōkai before. I wouldn't have thought to try that.
