### ISSUE TITLE
connection error for the Extension Manhwa18.cc

### ISSUE THREAD

**Issue by LazilyKen** [null2264/yokai#305]
### Steps to reproduce

![Screenshot_20241214-120710](https://github.com/user-attachments/assets/89b7e4d7-b2c3-4e2c-8623-98847fb2676f)

### Expected behavior

open the extension like normal but shown as connection error

### Actual behavior

Connection Error for the extension Manhwa18.cc but the website works completely fine

### Yōkai version

1.9.3

### Android version

Android 14

### Device

Infinix GT 20 Pro 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, or a request for an extension, I should be contacting the extensions repository's maintainer/support for help.
- [X] I am reporting an issue exclusive to this fork. I have also checked that is not an issue on the [main version of Mihon](https://github.com/mihonapp/mihon)
- [X] I have tried the [troubleshooting guide](https://mihon.app/help/).
- [X] I have updated the app to version **[1.9.3](https://github.com/null2264/yokai/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have filled out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
That's an personal internet-related issue, not an app-related issue.

Switch networks, use a VPN, adjust DNS over HTTPS in Yokai Menu > Settings > Advanced, remember to restart your app after adjusting this setting.

Otherwise, check with whoever/wherever you get your extensions from for any known issues
> If this is an issue with an extension, or a request for an extension, I should be contacting the extensions repository's maintainer/support for help.
