### ISSUE TITLE
Missing path

### ISSUE THREAD

**Issue by ZainVincennt** [null2264/yokai#312]
### Steps to reproduce

Open app-> hitomi extension-> advanced search-> click included and excluded as always

### Expected behavior

it should show me all result like manga/doujinshi with my chose tags

### Actual behavior

![Screenshot_2024-12-18-13-48-09-050_eu kanade tachiyomi yokai](https://github.com/user-attachments/assets/3493838f-e1f7-4939-903f-132859b9f36b)

### Yōkai version

1.9.6

### Android version

13

### Device

Poco f5 pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, or a request for an extension, I should be contacting the extensions repository's maintainer/support for help.
- [X] I am reporting an issue exclusive to this fork. I have also checked that is not an issue on the [main version of Mihon](https://github.com/mihonapp/mihon)
- [X] I have tried the [troubleshooting guide](https://mihon.app/help/).
- [X] I have updated the app to version **[1.9.6](https://github.com/null2264/yokai/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have filled out all of the requested information in this form.

**Comment by null2264** [comment]
Please confirm with the extension's maintainer that it is in fact app issue and not an extension issue nor a source issue before reporting extension-related issue. From the error listed above, it's most likely an extension issue.
