### ISSUE TITLE
Yokai 1.9.X and Up Crash when Newly Installed

### ISSUE THREAD

**Issue by w00ogly** [null2264/yokai#315]
### Steps to reproduce

1. Delete Old version before 1.9.0 or Clear Data of Newer Versions
2. Install Newer Version
3. App Doesn't Open

### Expected behavior

App Should Open to Set Up

### Actual behavior

Sometime Only Show logo but soon Crashes

### Yōkai version

1.9.6

### Android version

Android 14

### Device

Samsung Galaxy S22 Ultra

### Other details

App only works if updated from older version, but when you clear data or newly Install it doesn't open. This applies to all 1.9.0 Yokai Versions

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, or a request for an extension, I should be contacting the extensions repository's maintainer/support for help.
- [X] I am reporting an issue exclusive to this fork. I have also checked that is not an issue on the [main version of Mihon](https://github.com/mihonapp/mihon)
- [X] I have tried the [troubleshooting guide](https://mihon.app/help/).
- [X] I have updated the app to version **[1.9.6](https://github.com/null2264/yokai/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have filled out all of the requested information in this form.

**Comment by null2264** [comment]
Can you try [1.9.7 beta 1](https://github.com/null2264/yokai/releases/tag/v1.9.7-b1)?

**Comment by w00ogly** [comment]
> Can you try [1.9.7 beta 1](https://github.com/null2264/yokai/releases/tag/v1.9.7-b1)?

Crashed again
![Screenshot_20241221_184405_Ykai](https://github.com/user-attachments/assets/c3f0753f-1d49-4699-bc86-39d567c1f948)

**Comment by null2264** [comment]
Did it still closes if you tap "Wait"?

**Comment by w00ogly** [comment]
App freezes

https://github.com/user-attachments/assets/a1ce684b-e5d2-4ac2-9118-992f44f32424

**Comment by null2264** [comment]
Interesting...

**Comment by w00ogly** [comment]
I've circumvented the issue by downloading a pre-1.9.X Yokai Version (specifically Yōkai v1.8.5.13) if I do the set up there and then update the app works relatively normal after, just a bit slow.

**Comment by null2264** [comment]
Try [beta 2](https://github.com/null2264/yokai/releases/tag/v1.9.7-b2) maybe?

**Comment by w00ogly** [comment]
Works now

https://github.com/user-attachments/assets/ae4e0ff3-036e-4689-99b1-72a154e1d57c

**Comment by null2264** [comment]
Nice, I'll deploy it as stable tomorrow...
