### ISSUE TITLE
Bro am I tripping no hate to the developer

### ISSUE THREAD

**Issue by Fuzzythegoatq** [null2264/yokai#326]
### Steps to reproduce

Bro not one thing has changed since I haven't been using the app lately. Honestly might be the downfall of J2k. Was good while it lasted

### Expected behavior

A change

### Actual behavior

Literally nothing lol I'm just complaining bro😭 No fr why isn't there a new feature 

### Crash logs

.

### Yōkai version

.

### Android version

.

### Device

.

### Other details

.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, or a request for an extension, I should be contacting the extensions repository's maintainer/support for help.
- [X] I am reporting an issue exclusive to this fork. I have also checked that is not an issue on the [main version of Mihon](https://github.com/mihonapp/mihon)
- [X] I have tried the [troubleshooting guide](https://mihon.app/help/).
- [X] I have updated the app to version **[1.9.7](https://github.com/null2264/yokai/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have filled out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Go make your own app and/or make pull requests here if it's so easy

**Comment by null2264** [comment]
The main focus at the moment is to migrate the codebase to a more modern infrastructure, new features will be added once in awhile at random as stated in the README file.

If you really want certain features to be added, feel free to make a pull request.
