### ISSUE TITLE
Add Automatic Library Update In App

### ISSUE THREAD

**Issue by Fuzzythegoatq** [null2264/yokai#34]
### Describe your suggested feature

![Screenshot_2024-02-12-02-12-12-818](https://github.com/null2264/yokai/assets/124460008/71718be5-b94e-4f24-9a72-be5b5c52221e)
Been using Tachiyomi for about 6 months now. I was using comic (can't say full name) and i liked they had a feature for when i opened the site it would let me know when a need chapter was out.I have nothing else to say about Tachiyomi since is 'Nearly' perfect. Only complaint i have, is that i'm limited to "Auto Library Update." I just want a option where it can automatically update it when i'm opening the app so ion have to do all that.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an request for a feature in the original Tachiyomi, I am opening because multiple versions of Yōkai have been released without this feature.
- [X] If this is an issue with an extension, or a request for an extension, I should be contacting the extensions repository's maintainer/support for help.
- [X] I have updated the app to version **[1.7.14](https://github.com/null2264/yokai/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by null2264** [comment]
Sorry, I'm not sure I can add this as it may cause unnecessary burden on the source side to have it auto update everytime you open the app.

**Comment by Fuzzythegoatq** [comment]
> Sorry, I'm not sure I can add this as it may cause unnecessary burden on the source side to have it auto update everytime you open the app.

Fuck
