### ISSUE TITLE
Olympus again

### ISSUE THREAD

**Issue by Unknoweird** [null2264/yokai#39]
### Describe your suggested feature

Olympus Scanlation has changed the domain again 

### Other details

Where do I put the url change advise from earlier? (Sorry my English is trash) 

https://visorolym.com/

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an request for a feature in the original Tachiyomi, I am opening because multiple versions of Yōkai have been released without this feature.
- [X] If this is an issue with an extension, or a request for an extension, I should be contacting the extensions repository's maintainer/support for help.
- [X] I have updated the app to version **[1.7.14](https://github.com/null2264/yokai/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by null2264** [comment]
Extension issues should be reported to their respective repo. You should know where if you explicitly add them, otherwise Google is your best friend.

**Comment by Unknoweird** [comment]
I don't really understand. The page changed to that new domain, it isn't exactly an error, just an advise
