### ISSUE TITLE
Is the RAM management good?

### ISSUE THREAD

**Issue by mozzaru** [null2264/yokai#4]
### Steps to reproduce

I mean when you open an apk or browser for a moment and then return to the apk it suddenly relogs.

### Expected behavior

If it is, please fix the Ram management
Thanks 

### Actual behavior

.

### Crash logs

.

### Yōkai version

Last

### Android version

Android 11

### Device

Realme 7i

### Other details

.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I am reporting an issue exclusive to this fork. I have also checked that is not an issue on the [main version of Tachiyomi](https://github.com/tachiyomiorg/tachiyomi)
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.7.8](https://github.com/null2264/yokai/releases/latest)**.
- [X] I have updated all installed extensions.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I have filled out all of the requested information in this form.

**Comment by null2264** [comment]
Not sure what this means, but if what you meant is that the app couldn't run in the background then it's not really on the scope of this app, it's the phone's normal behaviour... You can try this guide to workaround it: https://dontkillmyapp.com, different phone handles RAM management differently.
