### ISSUE TITLE
Issue with split tall images.

### ISSUE THREAD

**Issue by Dinor** [null2264/yokai#41]
### Steps to reproduce

1. Enable split tall images
2. Download the chapter

### Expected behavior

Images are downloaded and split

### Actual behavior

Error: Couldn't Split Downloaded image

### Yōkai version

1.7.14

### Android version

Android 8.1

### Device

Xiaomi Mi Pad

### Other details

It works without any issues on TachiyomiSY and Mihon, however, in Yokai and TachiyomiJ2K there's an error. 
Is the method to split tall images different in Yokai and J2K compared to SY and Mihon? 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, or a request for an extension, I should be contacting the extensions repository's maintainer/support for help.
- [X] I am reporting an issue exclusive to this fork. I have also checked that is not an issue on the [main version of Mihon](https://github.com/mihonapp/mihon)
- [X] I have tried the [troubleshooting guide](https://mihon.app/help/).
- [X] I have updated the app to version **[1.7.14](https://github.com/null2264/yokai/releases/latest)**.
- [X] I have updated all installed extensions.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I have filled out all of the requested information in this form.

**Comment by null2264** [comment]
Seems to be false positive, it's checking if it should split the image, but for some reason Jay send notification that the image can't be split even tho in reality it's "This image is fine, I should not split this".
