### ISSUE TITLE
Somehow some extensions give an error that does not occur in other tachiyomi forks

### ISSUE THREAD

**Issue by edmxn** [null2264/yokai#42]
### Steps to reproduce

Open extension (in this case: tumangaonline, lector manga, traducciones amistosas and plot twist no fansub)
**THIS IS A YOKAI ISSUE, NO OF THE SOURCES**
I can confirm this because other users in other forks do not see this error

### Expected behavior

all should load normally, show mangas and shi, **_like all other forks do_**

### Actual behavior

_Q2xvdWRmbGFyZQ== (base64)_ error (idk if that bot is here)

### Yōkai version

1.7.14

### Android version

Android 12

### Device

Samsung S10+

### Other details

**THIS IS A YOKAI ISSUE, NO OF THE SOURCES**
I can confirm this because other users in other forks do not see this error

I have changed the user agent more than 15 times, including the ones that Google gives me on different devices of mine

This also happens in tachij2k, but I have no hope that whatever I report there will be done

I can't tell if I'm the only one with this problem

This error does not appears to me in mihon, or tachiyomisy, haven't really tried in others tbh

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, or a request for an extension, I should be contacting the extensions repository's maintainer/support for help.
- [X] I am reporting an issue exclusive to this fork. I have also checked that is not an issue on the [main version of Mihon](https://github.com/mihonapp/mihon)
- [X] I have tried the [troubleshooting guide](https://mihon.app/help/).
- [X] I have updated the app to version **[1.7.14](https://github.com/null2264/yokai/releases/latest)**.
- [X] I have updated all installed extensions.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I have filled out all of the requested information in this form.

**Comment by null2264** [comment]
Can you access the sources using WebView?

**Comment by edmxn** [comment]
> Can you access the sources using WebView? Those sources are blocked for me except for Plot Twist, and it works just fine on my end.

Yes, via WebView they are good working
Idk abt that blocked thing, they work fine in other forks
(It feels like I'm saying this fork is bad and others are better, **I'm not**, saying just in case)

**Comment by null2264** [comment]
Can you send screenshot of the issue?

> (It feels like I'm saying this fork is bad and others are better, I'm not, saying just in case)
Lmao, it's fine.

**Comment by edmxn** [comment]
> Can you send screenshot of the issue?
> 
> > (It feels like I'm saying this fork is bad and others are better, I'm not, saying just in case)
> 
> Lmao, it's fine.

W.T.F

![Screenshot_20240229_210216_Ykai](https://github.com/null2264/yokai/assets/101371218/c24647f6-2889-44c0-8da3-9267ab532e0a)
![Screenshot_20240229_210206_Ykai](https://github.com/null2264/yokai/assets/101371218/e7b9d04d-54f9-466c-bf83-5da4b25ad22a)

I just checked and it's fixed?!?!
Should this be closed? Idk

My guess is that, maybe after changing user agent you have to wait a few hours for it to take effect(?)
But the user agent I put in after testing the 15+ is the custom one I had at the beginning.... Seriously, W.T.F

**Comment by null2264** [comment]
Lmao, I assume it's just cloudflare being weird (nothing new honestly), I'll close it for now.
