### ISSUE TITLE
Page clutter when downloading chapters with the same tittle/name

### ISSUE THREAD

**Issue by lalalasupa0** [null2264/yokai#43]
### Steps to reproduce

Download two chapters with the same title

### Expected behavior

Once downloaded, the pages should look like this

CHAP. 01: LALALA -> pages: lala90, lala91

CHAP. 02: LALALA -> pages: lala92, lala93

### Actual behavior

They looks like this

CHAP. 01: LALALA -> pages: lala92, lala93

CHAP. 02: LALALA -> pages: lala90, lala91

### Yōkai version

1.7.14

### Android version

Android 12

### Device

Samsung S10+

### Other details

I asked in the discord of the extension repo and they said this:

> It's an issue with the app itself, it can't distinguish between downloaded chapters with the same tittle

This happens mostly in an extension of the web Kemono because many "chapters" have the same tittle, like there can be a lot of "Saitama"

The location where the pages end are not like that in the original source (in this case using Kemono as example)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, or a request for an extension, I should be contacting the extensions repository's maintainer/support for help.
- [X] I am reporting an issue exclusive to this fork. I have also checked that is not an issue on the [main version of Mihon](https://github.com/mihonapp/mihon)
- [X] I have tried the [troubleshooting guide](https://mihon.app/help/).
- [X] I have updated the app to version **[1.7.14](https://github.com/null2264/yokai/releases/latest)**.
- [X] I have updated all installed extensions.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I have filled out all of the requested information in this form.

**Comment by null2264** [comment]
Added an option to fix this, not yet tested thoroughly but seems to be working. You can try it on the nightly version, the option is on Settings > Download.

![Screenshot_2024_0528_141855](https://github.com/null2264/yokai/assets/46041660/38989c42-9ac8-4f91-a52c-8c247c12f48e)

![IMG-20240528-WA0002](https://github.com/null2264/yokai/assets/46041660/68497143-5b5e-4f51-9b49-ae6e8dfac1f4)

**Comment by lalalasupa0** [comment]
> Added an option to fix this, not yet tested thoroughly but seems to be working. You can try it on the nightly version, the option is on Settings > Download.
> 
> ![Screenshot_2024_0528_141855](https://private-user-images.githubusercontent.com/46041660/334307484-38989c42-9ac8-4f91-a52c-8c247c12f48e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY5NTA0NTUsIm5iZiI6MTcxNjk1MDE1NSwicGF0aCI6Ii80NjA0MTY2MC8zMzQzMDc0ODQtMzg5ODljNDItOWFjOC00ZjkxLWE1MmMtOGMyNDdjMTJmNDhlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI5VDAyMzU1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0YzdjN2QxNGNjYjllOTQxZjU2YzcyYTRjNDg2NzQzMDIzMDI3OWNjMjg3Y2UzM2MzOWU2YTZmZjI4ODdiZTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bDjiTsrsEkGZyR6qRT0a6I7NkfJ7gi6sO7IfakghW8c)
> 
> ![IMG-20240528-WA0002](https://private-user-images.githubusercontent.com/46041660/334307821-68497143-5b5e-4f51-9b49-ae6e8dfac1f4.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY5NTA0NTUsIm5iZiI6MTcxNjk1MDE1NSwicGF0aCI6Ii80NjA0MTY2MC8zMzQzMDc4MjEtNjg0OTcxNDMtNWI1ZS00ZjUxLTliNDktYWU2ZThkZmFjMWY0LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI5VDAyMzU1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI1MTgxZGJjYTE3YzUxMzA1OWM5M2Y1ZTFhNDAyY2Y1ZjYyM2M5MzA5NzZhM2Y0OWY4YWY4YjAzYTU0NDkxYjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6ciMNVjng_HBo-MDYHsUQF47ozxdSVS4wG4s-f8NirU)

IT DOES WORK!
Although there is a little flicker of the "loading" icon for a second, no big deal but I wanted to mention it.

For now I will stick to the nightly build, not sure if you can answer me here, but, is there any chance of losing library entries if I use this build of the app? Since it is for testing only and allat...

**Comment by null2264** [comment]
As long as you backup the app before updating, no, it'll work just like stable releases but with experimental features.

**Comment by null2264** [comment]
Closing this as the feature is now available on stable release.
