### ISSUE TITLE
Yokai Nightly update even when on latest

### ISSUE THREAD

**Issue by Xeiv** [null2264/yokai#44]
### Steps to reproduce

Open app

### Expected behavior

No update alert unless there's a new nightly update

### Actual behavior

Update alert for r4945 shows up even though the latest nightly version is installed. Also, sometimes I get an update alert for 1.7.14 too

### Yōkai version

Yokai Nightly r4945

### Android version

Android 14

### Device

Samsung Galaxy S21 Ultra

### Other details

Only happens on the nightly app 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, or a request for an extension, I should be contacting the extensions repository's maintainer/support for help.
- [X] I am reporting an issue exclusive to this fork. I have also checked that is not an issue on the [main version of Mihon](https://github.com/mihonapp/mihon)
- [X] I have tried the [troubleshooting guide](https://mihon.app/help/).
- [X] I have updated the app to version **[1.7.14](https://github.com/null2264/yokai/releases/latest)**.
- [X] I have updated all installed extensions.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I have filled out all of the requested information in this form.

**Comment by ImpenetrableNoble** [comment]
I get that notification alot as well on my a21 galaxy smartphone.

**Comment by null2264** [comment]
Fixed on https://github.com/null2264/yokai/commit/d30d03b6596c89017f159f46c3fa2df718600064, https://github.com/null2264/yokai/commit/08446de7f355340f950ef058fd1fe66680a07d0c, and https://github.com/null2264/yokai/commit/16c7e3c5714397bec02170c1d1adea56ed2002ac (r4954 or newer)
