### ISSUE TITLE
No pages found + Pages not showing in WebView in a specific extension

### ISSUE THREAD

**Issue by lalalasupa0** [null2264/yokai#45]
### Steps to reproduce

Open a chapter in source "Olympus Scanlation (Spanish)" by [Keiyoushi](https://keiyoushi.github.io/extensions)

### Expected behavior

Should show pages of chapter

### Actual behavior

"Pages not found"

### Yōkai version

1.8.3-b5156

### Android version

Android 12

### Device

Samsung S10+

### Other details

In Mihon that source open and load the pages of chapters with no problem, so is a yokai-only issue
This actually happens in TachiJ2K and TSY (not so sure) too

When opening the chapter in WebView, the pages are not visible
On the source web you do see the pages

It seems that the same thing happens with the RavenManga extension of the same language but less frequently and without the WebView thing

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, or a request for an extension, I should be contacting the extensions repository's maintainer/support for help.
- [X] I am reporting an issue exclusive to this fork. I have also checked that is not an issue on the [main version of Mihon](https://github.com/mihonapp/mihon)
- [X] I have tried the [troubleshooting guide](https://mihon.app/help/).
- [X] I have updated the app to version **[1.7.14](https://github.com/null2264/yokai/releases/latest)**.
- [X] I have updated all installed extensions.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I have filled out all of the requested information in this form.

**Comment by edmxn** [comment]
Idk if this happens in other sources of that repo

**Comment by null2264** [comment]
Closing, seems to be extension issue.
