### ISSUE TITLE
Application Icon 

### ISSUE THREAD

**Issue by Z46R3US** [null2264/yokai#5]
### Describe your suggested feature

Icon idea [Yokai Images](https://drive.google.com/drive/folders/198K1UbC56f4pnqQeXFmo2Q8Njdsf4E9h)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an request for a feature in the original Tachiyomi, I am opening because multiple versions of Yōkai have been released without this feature.
- [X] If this is an issue with an extension, or a request for an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[1.7.8](https://github.com/null2264/yokai/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by null2264** [comment]
The current icon is already based on a yōkai, Hitodama...

**Comment by Z46R3US** [comment]
> The current icon is already based on a yōkai, Hitodama...

Reworked on a ICON / LOGO based on Hitodama - [ICON](https://drive.google.com/drive/folders/19oIba5ITveFS4IupLSfU5IXgpvGKv-3q)
