### ISSUE TITLE
Yokai crashes everytime i open It

### ISSUE THREAD

**Issue by Super0Teah** [null2264/yokai#60]
### Steps to reproduce

1:Open the app

### Expected behavior

It should prompt me to my library as always

### Actual behavior

It just crashes

### Crash logs

I can't Open the app and couldn't find crash logs on the app folder

### Yōkai version

1.8.0

### Android version

Android 10

### Device

Samsung Galaxy S9+

### Other details

Yokai crashes everytime i open It, This could be related to a Mihon issue but in Mihon it's just slow Yokai directly crashes, That's why im making this report

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, or a request for an extension, I should be contacting the extensions repository's maintainer/support for help.
- [X] I am reporting an issue exclusive to this fork. I have also checked that is not an issue on the [main version of Mihon](https://github.com/mihonapp/mihon)
- [X] I have tried the [troubleshooting guide](https://mihon.app/help/).
- [X] I have updated the app to version **[1.8.0](https://github.com/null2264/yokai/releases/latest)**.
- [X] I have updated all installed extensions.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I have filled out all of the requested information in this form.

**Comment by null2264** [comment]
Have you completed the onboarding process or does it crash as soon as you update Yokai?

**Comment by Super0Teah** [comment]
It crashes as soon as you update Yokai, Had to uninstall and install it again to get It working

**Comment by null2264** [comment]
Interesting... I will just slap Mihon's crash screen to Yokai in case that happened again so I can debug it.

**Comment by null2264** [comment]
Took a wild guess, probably fixed by 7daa7cb7c9f5cf37c5985beaef316dd424654fe0.

**Comment by null2264** [comment]
Seems like it's fully fixed on [v1.8.0.2](https://github.com/null2264/yokai/releases/tag/v1.8.0.2).
