### ISSUE TITLE
Access to all files permission

### ISSUE THREAD

**Issue by AshbornXS** [null2264/yokai#61]
### Steps to reproduce

1. Install and setup the app normally
2. Try to download something, it will ask for "Access to all files" permission
3. Try to give it the permission

### Expected behavior

Be able to give it the permission

### Actual behavior

The option is greyed out

### Yōkai version

1.8.0.1

### Android version

Android 13

### Device

Xiaomi Redmi Note 8 Pro

### Other details

Not using MIUI so this isn't the problem

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, or a request for an extension, I should be contacting the extensions repository's maintainer/support for help.
- [X] I am reporting an issue exclusive to this fork. I have also checked that is not an issue on the [main version of Mihon](https://github.com/mihonapp/mihon)
- [X] I have tried the [troubleshooting guide](https://mihon.app/help/).
- [X] I have updated the app to version **[1.8.0.1](https://github.com/null2264/yokai/releases/latest)**.
- [X] I have updated all installed extensions.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I have filled out all of the requested information in this form.

**Comment by RaphielHS** [comment]
Up
Phone: Realme GT Master Edition (Andro 13)
![Screenshot_2024-05-27-23-50-13-27_fc704e6b13c4fb26bf5e411f75da84f2.jpg](https://github.com/null2264/yokai/assets/70839561/2259acc2-b4ce-44e1-8419-ccae8eedb73e)

**Comment by Sylent-Sys** [comment]
Phone : Itel RS4
Android Version : 13
Root : Not Rooted
![Screenshot_20240528-001546](https://github.com/null2264/yokai/assets/53076870/0571fded-7cbc-4d60-99e3-25a222d084f0)
![Screenshot_20240528-001602](https://github.com/null2264/yokai/assets/53076870/6cdac4c9-f2bb-4bd6-af5e-1d7fcaf5e302)

**Comment by Chioxi** [comment]
Same issue here, I can't find the app in "All files access"

Samsung A52

**Comment by MrDfour** [comment]
Came to ditto this, Poco X6 Pro, HyperOS over Android 14.
I'll try later in my A13 Poco X3 Pro to see if a custom rom is having the same issue

**Comment by AshbornXS** [comment]
no need, it's probably missing the permission on the manifest, will take a look soon, everyone with a12+ will have the same issue since google changed the permission needed to access files

**Comment by null2264** [comment]
Should be fix on b20d4a298a8c2aea7782b128acba648d29e89047. I'll release it later today, in the morning, you can try if it works on nightly version for now (once it finish compiling).

**Comment by AshbornXS** [comment]
worked, well you can't give it the permission yet but downloads are working just fine, so I think it's a win hahahaha thanks

**Comment by null2264** [comment]
Yea well, you no longer need that permission since Yokai use Tachi's unified storage... I just forgot to turn off the perm requests :v

**Comment by MrDfour** [comment]
Yep, solved it.
Android 11+ bros, heh gotta love the dev

**Comment by null2264** [comment]
Alright, fixed on [v1.8.0.2](https://github.com/null2264/yokai/releases/tag/v1.8.0.2) :+1:
