### ISSUE TITLE
Download "unread chapters" is not affected by scanlator filter

### ISSUE THREAD

**Issue by notXciting** [null2264/yokai#62]
### Steps to reproduce

1. Use comick extension.
2. Find a manga/manhwa with multiple sources/scanlators.
3. Filter the scanlators.
4. Click on download, then Unread chapters.

### Expected behavior

After I filter out the scanlators, and tap on download unread chapters it should only download the scanlators that i didn't select to be removed or filtered out.

### Actual behavior

After filtering the scanlators and tap on download unread chapters its still downloading even the filtered out chapters.

### Yōkai version

1.8.0.2

### Android version

Android 14

### Device

Samsung A52s

### Other details

This doesn't happen on TachiyomiSY.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, or a request for an extension, I should be contacting the extensions repository's maintainer/support for help.
- [X] I am reporting an issue exclusive to this fork. I have also checked that is not an issue on the [main version of Mihon](https://github.com/mihonapp/mihon)
- [X] I have tried the [troubleshooting guide](https://mihon.app/help/).
- [X] I have updated the app to version **[1.8.0.2](https://github.com/null2264/yokai/releases/latest)**.
- [X] I have updated all installed extensions.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I have filled out all of the requested information in this form.

**Comment by null2264** [comment]
Not sure if this can easily be done since J2K's scanlator filter is pretty messy, I'll halt this unleast till I modernize the database handler.
