### ISSUE TITLE
"An Unexpected Error Occurred" App crash (screenshot + crash log)

### ISSUE THREAD

**Issue by lalalasupa0** [null2264/yokai#65]
### Steps to reproduce

Not specific

### Expected behavior

It shouldn't crash ig

### Actual behavior

![Screenshot_20240529_161220_Ykai](https://github.com/null2264/yokai/assets/101371218/e9624a41-1816-4516-a6e4-588a128b0275)

### Crash logs

[yokai_crash_logs.txt](https://github.com/null2264/yokai/files/15491554/yokai_crash_logs.txt)

[yokai_crash_logs.txt](https://github.com/null2264/yokai/files/15491610/yokai_crash_logs.txt)

### Yōkai version

1.8.1

### Android version

Android 12

### Device

Samsung S10+

### Other details

This has happened to me twice, first time when I deleted an entry from my library and I thought adding the screenshot and crash log here would be better, but they seem to be different issues as the second time was while I was editing the description of a manga.
It's like the app feels overwhelmed by the actions lol.

*I tried again and yeah, it happens specifically when you delete an entry and when you edit a description

**The second thing only happens in the stable build, idk abt the first one

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, or a request for an extension, I should be contacting the extensions repository's maintainer/support for help.
- [X] I am reporting an issue exclusive to this fork. I have also checked that is not an issue on the [main version of Mihon](https://github.com/mihonapp/mihon)
- [X] I have tried the [troubleshooting guide](https://mihon.app/help/).
- [X] I have updated the app to version **[1.8.1](https://github.com/null2264/yokai/releases/latest)**.
- [X] I have updated all installed extensions.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I have filled out all of the requested information in this form.

**Comment by null2264** [comment]
The crash for deleting an entry will be tracked on GH-51

**Comment by lalalasupa0** [comment]
> The crash for deleting an entry will be tracked on [GH-51](https://github.com/null2264/yokai/issues/51)

If you're sure they are the same issue then it's cool

**Comment by null2264** [comment]
> > The crash for deleting an entry will be tracked on [GH-51](https://github.com/null2264/yokai/issues/51)
> 
> If you're sure they are the same issue then it's cool

I think so, I've had the same issue before and it just magically disappeared so I couldn't debug it, for the crash caused by editing an entry that one is a different issue.
