### ISSUE TITLE
Cannot 'save' pages from different chapters if they have the same name

### ISSUE THREAD

**Issue by lalalasupa0** [null2264/yokai#69]
### Steps to reproduce

Save one page of both chapters with the same name

### Expected behavior

Both should just appear in gallery

### Actual behavior

One overwrites the other

### Yōkai version

1.8.1.2-b5126

### Android version

Android 12

### Device

Samsung S10+

### Other details

If the page number is different this does not happen

I suppose it would be better to say that it might be better if it were possible to save the same page twice, then the second one should have a "_(1)" added to it to act as a copy, this way so as not to overwrite the other one

I believe other forks do that, Mihon too I think

This wouldn't necessarily be good as an absolute, since it's not inconvenient in other sources when you want to reorder saved pages and so forth.
But I think it would be nice if we could select whether to overwrite the previous page or copy it (from settings, of course)

* Using the Nighly Build

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, or a request for an extension, I should be contacting the extensions repository's maintainer/support for help.
- [X] I am reporting an issue exclusive to this fork. I have also checked that is not an issue on the [main version of Mihon](https://github.com/mihonapp/mihon)
- [X] I have tried the [troubleshooting guide](https://mihon.app/help/).
- [X] I have updated the app to version **[1.8.1.2](https://github.com/null2264/yokai/releases/latest)**.
- [X] I have updated all installed extensions.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I have filled out all of the requested information in this form.

**Comment by lalalasupa0** [comment]
@null2264 
It is still there (overwriting the previous page with the same name in gallery)
Or is there an option to enable for it to take effect? The new one in "Downloads" is already activated and it's still like this

**Comment by null2264** [comment]
Looks like I forgot to push one change, my internet being dumb right now so I'll have to wait for it to stabilise...

**Comment by null2264** [comment]
It went back to normal as soon I sent that, I just pushed the missing change

**Comment by lalalasupa0** [comment]
> It went back to normal as soon I sent that, I just pushed the missing change

Now it's works fine👍🏻

**Comment by null2264** [comment]
Lovely.
