### ISSUE TITLE
Stop untrusting sources (or new-added repositories specially)

### ISSUE THREAD

**Issue by lalalasupa0** [null2264/yokai#71]
### Describe your suggested feature

When I update a source, it gets marked as untrusted, it's annoying to have to mark them as trusted every time.
And, when you start a fresh start in the app, ALL of them are set as untrusted, as someone who has a LOT of sources, you can imagine...

### Other details

This is already implemented in Mihon (on advanced settings)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an request for a feature in the original Tachiyomi, I am opening because multiple versions of Yōkai have been released without this feature.
- [X] If this is an issue with an extension, or a request for an extension, I should be contacting the extensions repository's maintainer/support for help.
- [X] I have updated the app to version **[1.8.1.2](https://github.com/null2264/yokai/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by null2264** [comment]
It is in the backlog, just converted it to an issue on GH-72 for better tracking.
