### ISSUE TITLE
Sources updating too slowly or freezing up

### ISSUE THREAD

**Issue by lalalasupa0** [null2264/yokai#74]
### Steps to reproduce

Go to extensions
Update one or more

### Expected behavior

Should get you through the installation process quickly, like Mihon and others

### Actual behavior

The process freezes at a point, without advancing

### Yōkai version

1.8.1.2-b5131

### Android version

Android 12

### Device

Samsung S10+

### Other details

Updating the sources using another app may work, but the Yokai issue is still there

This happens to me using the default installer of the device, although I don't know if it has something to do with the problem, since the problem is in the process of downloading the source, or somewhere in between.
![Screenshot_20240602_142808_Ykai Nightly](https://github.com/null2264/yokai/assets/101371218/31582677-feec-4dc3-9223-9f2d683a7037)
Freezes here specifically, but also happens when in " pending" state.
I don't use Shizuku as I use the Secure Folder on my phone, where it can't be used.

This has been going on for a long time, even in TJ2K

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, or a request for an extension, I should be contacting the extensions repository's maintainer/support for help.
- [X] I am reporting an issue exclusive to this fork. I have also checked that is not an issue on the [main version of Mihon](https://github.com/mihonapp/mihon)
- [X] I have tried the [troubleshooting guide](https://mihon.app/help/).
- [X] I have updated the app to version **[1.8.1.2](https://github.com/null2264/yokai/releases/latest)**.
- [X] I have updated all installed extensions.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I have filled out all of the requested information in this form.

**Comment by lalalasupa0** [comment]
This doesn't happen anymore

**Comment by null2264** [comment]
Looks like adding a slight delay (around 0.5s - https://github.com/null2264/yokai/commit/97bd9c4bc8ade8e3b795c5fbca0617ade347d03f) to it fixed the issue. A long standing bug caused by Android 8+ changes
