### ISSUE TITLE
RavenManga Páginas no encontradas

### ISSUE THREAD

**Issue by Unknoweird** [null2264/yokai#76]
### Steps to reproduce

1. Entro a RavenManga
2. Elijo un webtoon
3. Pongo un capítulo 

### Expected behavior

Ver manhwa con normalidad 

### Actual behavior

En algunos manhwa no estan los capítulos, diciendo "Páginas no encontradas", como por ejemplo "La personaje de Webtoon"

### Yōkai version

TachiJ2K 1.7.14

### Android version

Android 10

### Device

Moto E6i

### Other details

No pasa con todos, como por ejemplo "Cazando con mis clones"

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, or a request for an extension, I should be contacting the extensions repository's maintainer/support for help.
- [X] I am reporting an issue exclusive to this fork. I have also checked that is not an issue on the [main version of Mihon](https://github.com/mihonapp/mihon)
- [X] I have tried the [troubleshooting guide](https://mihon.app/help/).
- [X] I have updated the app to version **[1.8.1.2](https://github.com/null2264/yokai/releases/latest)**.
- [X] I have updated all installed extensions.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I have filled out all of the requested information in this form.

**Comment by null2264** [comment]
1. Please use English (or Indonesia if you couldn't speak English), I only know these two lang.
2. Seems to be extension issue, please contact the extension maintainer instead.
3. This is Yokai, not J2K, you entered the wrong building.

**Comment by Unknoweird** [comment]
> 1. Please use English (or Indonesia if you couldn't speak English), I only know these two lang.
> 2. Seems to be extension issue, please contact the extension maintainer instead.
> 3. This is Yokai, not J2K, you entered the wrong building.

Sorry, I put TachiJ2K for accident. Where can I contact with the extension manteiner?
