### ISSUE TITLE
RavenManga missing pages

### ISSUE THREAD

**Issue by Unknoweird** [null2264/yokai#80]
### Steps to reproduce

1. Enter RavenManga extension 
2. Choose a Manhwa
3. Try to read a chapter 

### Expected behavior

Read normally 

### Actual behavior

Pages no found in some proyects (for example La personaje de webtoon, player, etc)

### Yōkai version

Yokai 1.8.2

### Android version

Android 10

### Device

Moto E6i

### Other details

It happens in some of them, not in every manhwa.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, or a request for an extension, I should be contacting the extensions repository's maintainer/support for help.
- [X] I am reporting an issue exclusive to this fork. I have also checked that is not an issue on the [main version of Mihon](https://github.com/mihonapp/mihon)
- [X] I have tried the [troubleshooting guide](https://mihon.app/help/).
- [X] I have updated the app to version **[1.8.2](https://github.com/null2264/yokai/releases/latest)**.
- [X] I have updated all installed extensions.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I have filled out all of the requested information in this form.

**Comment by null2264** [comment]
Have you confirm that this is not an extension issue?

**Comment by lalalasupa0** [comment]
> Have you confirm that this is not an extension issue?

It may be the same issue as
https://github.com/null2264/yokai/issues/45
I just check with the manhwa "PLAYER" on the source this issue mentioned and it's the same, not a web issue either

And, if this is the case, then it's Yokai-only (though I remember having this with TJ2K and TSY too,) I believe this doesn't happen with Mihon

**Comment by null2264** [comment]
>  I just checked with the manhwa "PLAYER" on the source this issue mentioned and it's the same, not a web issue either (using latest nightly build too)

Do you know which chapter did this happened? I tried first and latest and a few random chapters, couldn't replicate it.

**Comment by lalalasupa0** [comment]
> > I just checked with the manhwa "PLAYER" on the source this issue mentioned and it's the same, not a web issue either (using latest nightly build too)
> 
> Do you know which chapter did this happened? I tried first and latest and a few random chapters, couldn't replicate it.

Just tried again with the same chapter (205), It seems to be fixed after the source update, I guess the problem was in the repo after all?

Should I close the issue I mentioned before? If so I'll open other at the source repository

**Comment by null2264** [comment]
> Should I close the issue I mentioned before

Nah, I'll do it.

> I guess the problem was in the repo after all

Could be the website itself, I had the same issue with Comick since they delay the page for about an hour for certain scanlators and it took a few attempts for Yokai to invalidate the chapter I assume due to cache.
