### ISSUE TITLE
Add Music 

### ISSUE THREAD

**Issue by Fuzzythegoatq** [null2264/yokai#86]
### Describe your suggested feature

Add the music thing when you're reading Manhwas on Legal sites they have a music thing. I'd like that feature. (Webtoons)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an request for a feature in the original Tachiyomi, I am opening because multiple versions of Yōkai have been released without this feature.
- [X] If this is an issue with an extension, or a request for an extension, I should be contacting the extensions repository's maintainer/support for help.
- [X] I have updated the app to version **[1.8.3.4](https://github.com/null2264/yokai/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by AshbornXS** [comment]
just put on some music yourself lmao

**Comment by Fuzzythegoatq** [comment]
> just put on some music yourself lmao

I need that anime music custom made😤

**Comment by SSL-ACTX** [comment]
Wow, what a useless feature request. 💀

**Comment by Achyuth072** [comment]
Well it's not really a useless feature, as the webtoon app has custom music which changes based on the segment, yes music changes in a single chapter too.
I honestly don't how one would implement this, this was denied back in Tachiyomi and sitting dust in other forks as feature requests like this.
Well your best bet would if ever auto scroll is implemented like maybe the music can be synced with that.
Either way its a huge undertaking. But I'm all up for it.

**Comment by AshbornXS** [comment]
I don't think it's even possible to implement something like that, would probably be necessary to add a lot of things that would impact app performance, auto scroll is already on the backlog but I don't think that music feature would be something considered on future versions

if you want the music badly, sadly maybe it's just better to read directly from the website

**Comment by Achyuth072** [comment]
Honestly yes, the last thing anyone wants is performance dips. The reader apps for me has some hitches when I read long form content already this would just be another pain.
Well the best OP could do is rip the custom music hope it syncs with their scrolling.

**Comment by AshbornXS** [comment]
yeah, and other thing, maybe I'm wrong but I think that to add something like that would basically need an rework on both the app and the extensions, so even if the option is added on Yōkai maybe it won't be possible to use bcz the extensions doesn't support it

**Comment by Achyuth072** [comment]
> yeah, and other thing, maybe I'm wrong but I think that to add something like that would basically need an rework on both the app and the extensions, so even if the option is added on Yōkai maybe it won't be possible to use bcz the extensions doesn't support it

No you're I think rather working on the Yokai its best work on the Webtoons extensions itself since that's the source with custom music. Reworking the whole app for custom music for very few titles would not be efficient.

Well I guess OP has to take this to that extension's creator see what they say.

**Comment by null2264** [comment]
It is possible to inject my own function to support BGM to certain exts, J2K has SY's delegated source feature, but I'm not sure if I want to jump to audio player rabbit hole... It's probably less painful than video player, but I don't think it's worth it tbh... I haven't even used Webtoon ext for years.
