### ISSUE TITLE
"Show Content in Cutout Area" setting 

### ISSUE THREAD

**Issue by PotatoGuy23** [null2264/yokai#9]
### Describe your suggested feature

In Mihon and TachiyomiSY, there is a setting under reader called "Show content in cutout area" which when turned off, only shows content under the cutout area on phones with notches. I think this is a great feature and would love to see it implemented in Yokai.
![Screenshot_20240126_041109_TachiyomiSY](https://github.com/null2264/yokai/assets/156033972/9be686c0-8c0c-4ae9-b077-ea13c58ea3d4)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an request for a feature in the original Tachiyomi, I am opening because multiple versions of Yōkai have been released without this feature.
- [X] If this is an issue with an extension, or a request for an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[1.7.10](https://github.com/null2264/yokai/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by null2264** [comment]
Added in [r4888](https://github.com/null2264/yokai/releases/tag/r4888), not yet tested as I need to free up some storage...
