### ISSUE TITLE
Ability to turn off Smart Updates

### ISSUE THREAD

**Issue by w00ogly** [null2264/yokai#94]
### Describe your suggested feature

Mihon has the ability to turn off, "Predict Next Release Time", one of the features of Smart Update

### Other details

In Library, Skip Udpating Titles I have both the first and second box unchecked, Unread and Not Started. I have around 450 series "started", after the update the number of series quintupled despite my setting being the same. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an request for a feature in the original Tachiyomi, I am opening because multiple versions of Yōkai have been released without this feature.
- [X] If this is an issue with an extension, or a request for an extension, I should be contacting the extensions repository's maintainer/support for help.
- [X] I have updated the app to version **[1.8.4](https://github.com/null2264/yokai/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by null2264** [comment]
Could be a bug, Tachi level of smart updates is not yet implemented...

**Comment by w00ogly** [comment]
![Screenshot_20240611_172937_Ykai](https://github.com/null2264/yokai/assets/111436425/c999c09e-a913-47a8-a883-1edee08e8e0c)

I use the ongoing filter and it matched the number of series being updated.

![Screenshot_20240611_172946_Ykai](https://github.com/null2264/yokai/assets/111436425/ab036fb0-138d-48a8-b5dc-e06517c58177)

**Comment by w00ogly** [comment]
Then it likely a bug with the second box cause I toggled it on and off and it remained 2227. I also toggled the first one and it was accurate.
