### ISSUE TITLE
Titles from Komga source showing no unread chapter badge despite having unread chapters

### ISSUE THREAD

**Issue by swaggyP36000** [null2264/yokai#95]
### Steps to reproduce

Update to latest version of app

### Expected behavior

Titles from Komga with unread chapters should have the unread chapter badge

### Actual behavior

All titles from Komga show no unread chapters badge, despite having unread chapters. Even marking as read/unread doesn't change this

### Yōkai version

1.8.4

### Android version

Android 14

### Device

Samsung S21

### Other details

This doesn't appear to be an extension issue, as I have installed Yokai v1.8.3.4 and this issue doesn't exist there

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, or a request for an extension, I should be contacting the extensions repository's maintainer/support for help.
- [X] I am reporting an issue exclusive to this fork. I have also checked that is not an issue on the [main version of Mihon](https://github.com/mihonapp/mihon)
- [X] I have tried the [troubleshooting guide](https://mihon.app/help/).
- [X] I have updated the app to version **[1.8.4](https://github.com/null2264/yokai/releases/latest)**.
- [X] I have updated all installed extensions.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I have filled out all of the requested information in this form.

**Comment by Nitrousoxide** [comment]
Can confirm I'm seeing this as well on my install.  Unread badges **do** work on other sources for me, just not Komga.
